[GameModes]
0=Battle
1=Blitz
2=Cooperative
3=Land Rush
4=Meat Grinder
5=Megawealth
6=Mod Maps
7=Naval War
8=Oil In Centre
9=RA2 Ladder
10=Standard
11=Survival
12=Unholy Alliance
13=YR Ladder

[Oil In Centre]
CustomIniPath=INI\Map Code\Standard.ini
ForcedOptions=Oil In CentreForcedOptions
ForcedSpawnIniOptions=Oil In CentreForcedSpawnIniOptions

[Oil In CentreForcedOptions]
chkAutoRepair=false

[Oil In CentreForcedSpawnIniOptions]
GameMode=1

[Battle]
CustomIniPath=INI\Map Code\Standard.ini
ForcedSpawnIniOptions=BattleForcedSpawnIniOptions

[BattleForcedSpawnIniOptions]
GameMode=1

; The settings for RA2 Ladder
[RA2 Ladder]
CustomIniPath=INI\Map Code\RA2 Ladder.ini
ForcedOptions=RA2 LadderForcedOptions
ForcedSpawnIniOptions=RA2 LadderForcedSpawnIniOptions

[RA2 LadderForcedOptions]
chkShortGame=true
chkRedeplMCV=true
cmbCratesModifier=0
chkCrates=false
chkIngameAllying=true
cmbAIModifier=0
chkDestrBridges=true
chkDisableSuperWeapons=false
cmbSuperWeaponsModifier=0
chkBuildOffAlly=true
chkNoSpawnPreviews=false
cmbCredits=5
cmbStartingUnits=10
chkRA2Mode=true
chkNoYuri=false
chkNoFrance=false
chkNoSpy=false
chkBalancePatch=false
chkMultiEng=true
chkNoDogEngiEat=true
chkAutoRepair=false

[RA2 LadderForcedSpawnIniOptions]
GameMode=1

; The settings for Yuri's Revenge Quick Match
[YR Ladder]
CustomIniPath=INI\Map Code\YR Ladder.ini
ForcedOptions=YR LadderForcedOptions
ForcedSpawnIniOptions=YR LadderForcedSpawnIniOptions

[YR LadderForcedOptions]
chkShortGame=true
chkRedeplMCV=true
cmbCratesModifier=0
chkCrates=false
chkIngameAllying=true
cmbAIModifier=0
chkDestrBridges=true
chkBuildOffAlly=true
chkNoSpawnPreviews=false
cmbCredits=5
cmbStartingUnits=10
chkRA2Mode=false
chkNoYuri=false
chkNoFrance=false
chkNoSpy=false
chkBalancePatch=false
chkAutoRepair=false

[YR LadderForcedSpawnIniOptions]
GameMode=1

[Cooperative]
CustomIniPath=INI\Map Code\Cooperative.ini
ForcedOptions=CooperativeForcedOptions
ForcedSpawnIniOptions=CooperativeForcedSpawnIniOptions
MultiplayerOnly=yes

[CooperativeForcedOptions]
CoopDifficultyLevel=2
chkShortGame=false
chkRedeplMCV=true
cmbCratesModifier=0
chkCrates=false
chkMultiEng=false
chkIngameAllying=false
chkNoDogEngiEat=false
cmbAIModifier=0
chkDestrBridges=True
chkBuildOffAlly=true
chkRA2Mode=false
chkNoSpawnPreviews=false
cmbCredits=5
cmbStartingUnits=10
chkNoSpy=false
chkNoYuri=false
chkNoFrance=false
chkBalancePatch=false

[CooperativeForcedSpawnIniOptions]
GameMode=3

[Unholy Alliance]
CustomIniPath=INI\Map Code\Unholy Alliance.ini
ForcedSpawnIniOptions=Unholy AllianceForcedSpawnIniOptions

[Unholy AllianceForcedSpawnIniOptions]
GameMode=4

[Megawealth]
CustomIniPath=INI\Map Code\Megawealth.ini
ForcedSpawnIniOptions=MegawealthForcedSpawnIniOptions

[MegawealthForcedSpawnIniOptions]
GameMode=5

[Land Rush]
CustomIniPath=INI\Map Code\Land Rush.ini
ForcedSpawnIniOptions=Land RushForcedSpawnIniOptions

[Land RushForcedSpawnIniOptions]
GameMode=6

[Meat Grinder]
CustomIniPath=INI\Map Code\Meat Grinder.ini
ForcedSpawnIniOptions=Meat GrinderForcedSpawnIniOptions

[Meat GrinderForcedSpawnIniOptions]
GameMode=7

[Naval War]
CustomIniPath=INI\Map Code\Naval War.ini
ForcedSpawnIniOptions=Naval WarForcedSpawnIniOptions

[Naval WarForcedSpawnIniOptions]
GameMode=8

[Mod Maps]
CustomIniPath=INI\Map Code\Mod Maps.ini
ForcedOptions=ModMapsForcedOptions
ForcedSpawnIniOptions=ModMapsForcedSpawnIniOptions

[ModMapsForcedOptions]

[ModMapsForcedSpawnIniOptions]
GameMode=1

[Blitz]
CustomIniPath=INI\Map Code\Blitz_2v2.ini
ForcedOptions=BlitzForcedOptions
ForcedSpawnIniOptions=BlitzForcedSpawnIniOptions

[BlitzForcedOptions]
chkShortGame=true
chkRedeplMCV=true
cmbCratesModifier=0
chkCrates=false
chkIngameAllying=true
cmbAIModifier=0
chkDestrBridges=true
chkBuildOffAlly=true
chkNoSpawnPreviews=false
cmbStartingUnits=10
chkRA2Mode=false
chkNoYuri=false
chkNoFrance=false
chkNoSpy=false
chkBalancePatch=false
chkMultiEng=true
chkAutoRepair=false

[BlitzForcedSpawnIniOptions]
GameMode=1
