;-------------------------------------------------------------------------------------------------------------
; INI Control File for additional artmd entries for community maps.
; Any and all additions should only be used for custom maps. It should NEVER be noticeable or seen in vanilla.
;
; All assets used and provided by the community **MUST** be for public use and free of copyright restrictions.
; After making changes here and submitting them to the CNC-Net YR repository, please wait for approval.
;
; Try to keep this file clean and organized for future contributors.
; Below is an example of how to create a clone of the GI unit with a different cameo.
;
; Created by the CNCNet community.
;-------------------------------------------------------------------------------------------------------------

; [STRONGER_GI]
; Image=GI
; CameoPCX=supergiicon.pcx
; AltCameoPCX=supergiico.pcx
; Sequence=GISequence
; Crawls=yes
; Remapable=yes
; FireUp=2
; PrimaryFireFLH=80,0,105
; SecondaryFireFLH=80,0,90

[SGUNSHIP] ; Spectre Gunship v5.0 THIS NOT CUSTOM CAMEO, Usage of PDPLANE/CARGOPLANE cameo on a vehicle type unit because can't overwrite [AircraftTypes]
Cameo=OBMBICON
Image=orcab
Voxel=yes
PrimaryFireFLH=0,32,0
DisableVoxelCache=yes
DisableShadowCache=yes

[NUKEEM] ; Tactical Nuke MiG
Voxel=yes
Remapable=yes
Image=BPLN
CameoPCX=mig35mfi.pcx
AltCameoPCX=mig35mfi.pcx
PrimaryFireFLH=25,100,0

[OPERATOR]
CameoPCX=operator.pcx
AltCameoPCX=operator.pcx
Sequence=SealSequence
Crawls=yes
Remapable=yes
Image=SEAL
FireUp=3
PrimaryFireFLH=100,0,100

[PRISMOPERATOR]
CameoPCX=laser operator.pcx
AltCameoPCX=laser operator.pcx
Image=SEALA
Sequence=SealSequence
Crawls=yes
Remapable=yes
FireUp=3
PrimaryFireFLH=100,0,100

;[SCHD] ; original deployed siege chooper added vet cameo 
;Cameo=SCHPICON
;AltCameo=SCHPUICO
;Voxel=yes
;UseBuffer=yes
;Remapable=yes
;PrimaryFireFLH=200,0,250
;SecondaryFireFLH=200,0,250

;[FIREBASE]
;Remapable=yes
;Normalized=yes
;Cameo=firebaseicon.pcx
;Foundation=2x2
;Height=8
;DemandLoadBuildup=true
;NewTheater=yes
;CanHideThings=True
;CanBeHidden=False

[B2BOMBER]
Voxel=yes
Remapable=yes
CameoPCX=stealth bomber.pcx
Image=FORTRESS
AltCameoPCX=stealth bomber.pcx
PrimaryFireFLH=25,100,0

;[ALLIEDTANK]
;Cameo=tankcustoma.pcx
;AltCameo=tankcustoma.pcx
;Voxel=yes
;Remapable=yes
;PrimaryFireFLH=150,0,100