[ExtrasWindow]
DrawBorders=false
Size=800,600
BackgroundTexture=MainMenu\mainmenubg.png

[ExtraPictureBoxes]

[btnExCancel]
Location=645,535
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
Text=Back
ForeColor=255,255,0
Font=Arial,Bold,9.25
ForeColor=230,230,230
FontIndex=1
TextColorIdle=230,230,230
TextColorHover=255,255,255


[ExtraControls]

; ==========================
; Hidden Buttons
; ==========================
[btnExCredits]
Visible=false

[btnExStatistics]
Visible=false

[btnExMapEditor]
Visible=false
