;-------------------------------------------------------------------------------------------------------------
; INI Control File for additional artmd entries for community maps.
; Any and all additions should only be used for custom maps. It should NEVER be noticeable or seen in vanilla.
;
; All assets used and provided by the community **MUST** be for public use and free of copyright restrictions.
; After making changes here and submitting them to the CNC-Net YR repository, please wait for approval.
;
; Try to keep this file clean and organized for future contributors.
; Below is an example of how to create a clone of the GI unit with a different cameo.
;
; Created by the CNCNet community.
;-------------------------------------------------------------------------------------------------------------

; [STRONGER_GI]
; Image=GI
; CameoPCX=supergiicon.pcx
; AltCameoPCX=supergiico.pcx
; Sequence=GISequence
; Crawls=yes
; Remapable=yes
; FireUp=2
; PrimaryFireFLH=80,0,105
; SecondaryFireFLH=80,0,90

[CGBUNK05]; Bunker added by McPwny
CameoPCX=concretebunker.pcx; PCX Cameo created by Dr. Greenthumb
Foundation=2x2
Height=4
NewTheater=yes
DemandLoad=true
Buildup=CGBUNK05MK
MuzzleFlash0=-33,13
MuzzleFlash1=-22,19
MuzzleFlash2=-7,23
MuzzleFlash3=7,24
MuzzleFlash4=20,17
MuzzleFlash5=31,11
DamageFireOffset0=-29,22
DamageFireOffset1=24,0
CanHideThings=true
CanBeHidden=false
OccupyHeight=0
DemandLoadBuildup=true
FreeBuildup=true

[GATECH01]; Allied battle lab remake by Volkov_T-666
Remapable=yes
Normalized=yes
Cameo=GATECHICON
Height=12
Foundation=3x2
Buildup=GATECH01MK
DemandLoadBuildup=true
FreeBuildup=true
NewTheater=yes
ActiveAnim=GATECH01_A
ActiveAnimDamaged=GATECH01_AD
ActiveAnimZAdjust=-120
CanHideThings=True
CanBeHidden=False
OccupyHeight=5
DamageFireOffset0=-26,27
DamageFireOffset1=-2,-57
DamageFireOffset2=22,50

[GATECH01_A]
Image=GATECH01_A
Normalized=yes
Start=1
LoopStart=1
LoopEnd=12
LoopCount=-1
Rate=250
Layer=ground
NewTheater=yes

[GATECH01_AD]
Image=GATECH01_AD
Normalized=yes
Start=13
LoopStart=13
LoopEnd=24
LoopCount=-1
Rate=250
Layer=ground
NewTheater=yes

[NAGIGAT]; Soviet tesla structure by McPwny
Normalized=yes
Remapable=yes
Cameo=GIGAICON
Foundation=4x4
Buildup=NAGIGATMK
DemandLoadBuildup=true
FreeBuildup=true
NewTheater=yes
Height=6
OccupyHeight=4
CanHideThings=True
CanBeHidden=False
ZShapePointMove=60,60; the whole shit is fudged down to let tesla bolts draw OVER the building. 
DamageFireOffset0=12,85
DamageFireOffset1=-62,27
MuzzleFlash0=-62,-33; flash points are the little tesla coil tops
MuzzleFlash1=-20,8
MuzzleFlash2=58,-15
MuzzleFlash3=-63,-16
MuzzleFlash4=16,8
MuzzleFlash5=62,-33
MuzzleFlash6=-19,-41
MuzzleFlash2=17,-41
SuperAnim=NAGIGAT_SA; idling
SuperAnimDamaged=NAGIGAT_SAD
SuperAnimZAdjust=-120
SuperAnimYSort=-150
SuperAnimTwo=NAGIGAT_SB; power up
SuperAnimTwoDamaged=NAGIGAT_SBD
SuperAnimTwoZAdjust=-120
SuperAnimTwoYSort=-150
SuperAnimThree=NAGIGAT_SC; powered up
SuperAnimThreeDamaged=NAGIGAT_SCD
SuperAnimThreeZAdjust=-120
SuperAnimThreeYSort=-150
SuperAnimFour=NAGIGAT_SD; power down
SuperAnimFourDamaged=NAGIGAT_SDD
SuperAnimFourZAdjust=-120
SuperAnimFourYSort=-150
ActiveAnim=NAGIGAT_A; bottom half
ActiveAnimDamaged=NAGIGAT_AD
ActiveAnimZAdjust=-60
ActiveAnimYSort=120
ActiveAnimTwo=NAGIGAT_G; little side coils
;ActiveAnimTwoDamaged=NAGIGAT_GD
ActiveAnimTwoZAdjust=-70
ActiveAnimTwoYSort=150

[NAGIGAT_G]; tesla coil array
Normalized=yes
NewTheater=yes
Layer=ground
Start=0
LoopStart=0
LoopEnd=16
LoopCount=-1
Rate=220
ShouldUseCellDrawer=false
CustomPalette=palette.pal

[NAGIGAT_A]; bottom half of the building
Normalized=yes
NewTheater=yes
Layer=ground
Start=0
LoopStart=0
LoopEnd=16
LoopCount=-1
Rate=220

[NAGIGAT_AD]; bottom half of the building, damaged
Normalized=yes
NewTheater=yes
Layer=ground
Start=0
LoopStart=0
LoopEnd=16
LoopCount=-1
Rate=220

[NAGIGAT_SA]; idling
Normalized=yes
Start=0
LoopStart=0
LoopEnd=11
LoopCount=-1
Rate=200
Layer=ground
NewTheater=yes
Shadow=no
ShouldUseCellDrawer=false; forces it to not inherit the buildings pal and use anim pal instead
CustomPalette=palette.pal; forces it to not inherit anim pal and use the custom one instead 

[NAGIGAT_SAD]; idling damaged
Normalized=yes
Start=0
LoopStart=0
LoopEnd=11
LoopCount=-1
Rate=200
Layer=ground
NewTheater=yes
Shadow=no
ShouldUseCellDrawer=false
CustomPalette=palette.pal; yes, the palletes name is palette.pal

[NAGIGAT_SB]; powerup
Normalized=yes
Start=0
End=11
Rate=200
Layer=ground
NewTheater=yes
Shadow=no
StartSound=WeatherControlReady
ShouldUseCellDrawer=false
CustomPalette=palette.pal

[NAGIGAT_SBD]; powerup damaged
Normalized=yes
Start=0
End=11
Rate=200
Layer=ground
NewTheater=yes
Shadow=no
StartSound=WeatherControlReady
ShouldUseCellDrawer=false
CustomPalette=palette.pal

[NAGIGAT_SC]; powered
Normalized=yes
Start=0
LoopStart=0
LoopEnd=11
LoopCount=-1
Rate=200
Layer=ground
NewTheater=yes
Shadow=no
StartSound=WeatherControlReadyLoop
ShouldUseCellDrawer=false
CustomPalette=palette.pal

[NAGIGAT_SCD]; powered damaged
Normalized=yes
Start=0
LoopStart=0
LoopEnd=11
LoopCount=-1
Rate=200
Layer=ground
NewTheater=yes
Shadow=no
StartSound=WeatherControlReadyLoop
ShouldUseCellDrawer=false
CustomPalette=palette.pal

[NAGIGAT_SD]; powerdown
Normalized=yes
Start=0
End=11
Rate=200
Layer=ground
NewTheater=yes
Shadow=no
ShouldUseCellDrawer=false
CustomPalette=palette.pal

[NAGIGAT_SDD]; powerdown damaged
Normalized=yes
Start=0
End=11
Rate=200
Layer=ground
NewTheater=yes
Shadow=no
ShouldUseCellDrawer=false
CustomPalette=palette.pal

[SGUNSHIP] ; Spectre Gunship v5.0 THIS NOT CUSTOM CAMEO, Usage of PDPLANE/CARGOPLANE cameo on a vehicle type unit because can't overwrite [AircraftTypes]
Cameo=OBMBICON
Image=orcab
Voxel=yes
PrimaryFireFLH=0,32,0
DisableVoxelCache=yes
DisableShadowCache=yes

[NUKEEM] ; Tactical Nuke MiG
Voxel=yes
Remapable=yes
Image=BPLN
CameoPCX=mig35mfi.pcx
AltCameoPCX=mig35mfi.pcx
PrimaryFireFLH=25,100,0

[OPERATOR]
CameoPCX=operator.pcx
AltCameoPCX=operator.pcx
Sequence=SealSequence
Crawls=yes
Remapable=yes
Image=SEAL
FireUp=3
PrimaryFireFLH=100,0,100

[PRISMOPERATOR]
CameoPCX=laser operator.pcx
AltCameoPCX=laser operator.pcx
Image=SEALA
Sequence=SealSequence
Crawls=yes
Remapable=yes
FireUp=3
PrimaryFireFLH=100,0,100

[B2BOMBER]
Voxel=yes
Remapable=yes
CameoPCX=stealth bomber.pcx
Image=FORTRESS
AltCameoPCX=stealth bomber.pcx
PrimaryFireFLH=25,100,0
