;-------------------------------------------------------------------------------------------------------------
; INI Control File for additional artmd entries for community maps.
; Any and all additions should only be used for custom maps. It should NEVER be noticeable or seen in vanilla.
;
; All assets used and provided by the community **MUST** be for public use and free of copyright restrictions.
; After making changes here and submitting them to the CNC-Net YR repository, please wait for approval.
;
; Try to keep this file clean and organized for future contributors.
; Below is an example of how to create a clone of the GI unit with a different cameo.
;
; Created by the CNCNet community.
;-------------------------------------------------------------------------------------------------------------

; [STRONGER_GI]
; Image=GI
; CameoPCX=supergiicon.pcx
; AltCameoPCX=supergiico.pcx
; Sequence=GISequence
; Crawls=yes
; Remapable=yes
; FireUp=2
; PrimaryFireFLH=80,0,105
; SecondaryFireFLH=80,0,90

[CGBUNK05]; Bunker added by McPwny
Foundation=2x2
Height=4
NewTheater=yes
DemandLoad=true
Buildup=CGBUNK05MK
MuzzleFlash0=-33,13
MuzzleFlash1=-22,19
MuzzleFlash2=-7,23
MuzzleFlash3=7,24
MuzzleFlash4=20,17
MuzzleFlash5=31,11
DamageFireOffset0=-29,22
DamageFireOffset1=24,0
CanHideThings=true
CanBeHidden=false
OccupyHeight=0
DemandLoadBuildup=true
FreeBuildup=true

[SGUNSHIP] ; Spectre Gunship v5.0 THIS NOT CUSTOM CAMEO, Usage of PDPLANE/CARGOPLANE cameo on a vehicle type unit because can't overwrite [AircraftTypes]
Cameo=OBMBICON
Image=orcab
Voxel=yes
PrimaryFireFLH=0,32,0
DisableVoxelCache=yes
DisableShadowCache=yes

[NUKEEM] ; Tactical Nuke MiG
Voxel=yes
Remapable=yes
Image=BPLN
CameoPCX=mig35mfi.pcx
AltCameoPCX=mig35mfi.pcx
PrimaryFireFLH=25,100,0

[OPERATOR]
CameoPCX=operator.pcx
AltCameoPCX=operator.pcx
Sequence=SealSequence
Crawls=yes
Remapable=yes
Image=SEAL
FireUp=3
PrimaryFireFLH=100,0,100

[PRISMOPERATOR]
CameoPCX=laser operator.pcx
AltCameoPCX=laser operator.pcx
Image=SEALA
Sequence=SealSequence
Crawls=yes
Remapable=yes
FireUp=3
PrimaryFireFLH=100,0,100

[B2BOMBER]
Voxel=yes
Remapable=yes
CameoPCX=stealth bomber.pcx
Image=FORTRESS
AltCameoPCX=stealth bomber.pcx
PrimaryFireFLH=25,100,0
