;-------------------------------------------------------------------------------------------------------------
; INI Control File for additional artmd entries for community maps.
; Any and all additions should only be used for custom maps. It should NEVER be noticeable or seen in vanilla.
;
; All assets used and provided by the community **MUST** be for public use and free of copyright restrictions.
; After making changes here and submitting them to the CNC-Net YR repository, please wait for approval.
;
; Try to keep this file clean and organized for future contributors.
; Below is an example of how to create a clone of the GI unit with a different cameo.
;
; Created by the CNCNet community.
;-------------------------------------------------------------------------------------------------------------

; [STRONGER_GI]
; Image=GI
; CameoPCX=supergiicon.pcx
; AltCameoPCX=supergiico.pcx
; Sequence=GISequence
; Crawls=yes
; Remapable=yes
; FireUp=2
; PrimaryFireFLH=80,0,105
; SecondaryFireFLH=80,0,90

[SGUNSHIP] ; Spectre Gunship v5.0 THIS NOT CUSTOM CAMEO, Usage of PDPLANE/CARGOPLANE cameo on a vehicle type unit because can't overwrite [AircraftTypes]
Cameo=OBMBICON
Image=orcab
Voxel=yes
PrimaryFireFLH=0,32,0
DisableVoxelCache=yes
DisableShadowCache=yes

[NUKEEM] ; Tactical Nuke MiG
Voxel=yes
Remapable=yes
Image=BPLN
CameoPCX=mig35mfi.pcx
AltCameoPCX=mig35mfi.pcx
PrimaryFireFLH=25,100,0

[OPERATOR]
CameoPCX=operator.pcx
AltCameoPCX=operator.pcx
Sequence=SealSequence
Crawls=yes
Remapable=yes
Image=SEAL
FireUp=3
PrimaryFireFLH=100,0,100

[PRISMOPERATOR]
CameoPCX=laser operator.pcx
AltCameoPCX=laser operator.pcx
Image=SEALA
Sequence=SealSequence
Crawls=yes
Remapable=yes
FireUp=3
PrimaryFireFLH=100,0,100

[B2BOMBER] ; By MoamenMagdy
Voxel=yes
Remapable=yes
CameoPCX=stealth bomber.pcx
Image=FORTRESS
AltCameoPCX=stealth bomber.pcx
PrimaryFireFLH=25,100,0

[GAPDRONE] ; Chaos drone in water with Gap Drone text By MoamenMagdy
Voxel=yes
Remapable=yes
CameoPCX=gapdrone.pcx
Image=STNK
AltCameoPCX=gapdrone.pcx
PrimaryFireFLH=25,100,0

[ECMBOAT] ; By MoamenMagdy
Voxel=yes
Remapable=yes
CameoPCX=ecmboat.pcx
Image=SONIC
AltCameoPCX=ecmboat.pcx
PrimaryFireFLH=150,0,100

[RADARBOAT] ; By MoamenMagdy
Voxel=yes
Remapable=yes
CameoPCX=radarboat.pcx
Image=MRJ
AltCameoPCX=radarboat.pcx
PrimaryFireFLH=25,100,0

[WROBO] ; Robot Tank Water background By MoamenMagdy
Voxel=yes
Remapable=yes
CameoPCX=wrobo.pcx
Image=ROBO
AltCameoPCX=wrobo.pcx
PrimaryFireFLH=150,0,100

[DBOAT] ; By MoamenMagdy
Voxel=yes
Remapable=yes
CameoPCX=demoboat.pcx
Image=TUG
AltCameoPCX=demoboat.pcx
PrimaryFireFLH=25,100,0

[RDRONE]
Voxel=yes
Remapable=yes
CameoPCX=repairdrone.pcx
Image=dpod
AltCameoPCX=repairdrone.pcx
PrimaryFireFLH=25,100,0

[NUKESUB] ; By MoamenMagdy
Voxel=yes
CameoPCX=nukesub.pcx
Image=ZEP
AltCameoPCX=nukesub.pcx
PrimaryFireFLH=-50,0,-140

[MONEYBOAT] ; By MoamenMagdy
Voxel=yes
Remapable=yes
CameoPCX=moneygen.pcx
AltCameoPCX=moneygen.pcx
PrimaryFireFLH=25,100,0
Image=PCV

[CCOMANCHE] ; By MoamenMagdy
CameoPCX=cryoheli.pcx
AltCameoPCX=cryoheli.pcx
Voxel=yes
UseBuffer=yes
DisableVoxelCache=yes
DisableShadowCache=yes
Remapable=yes
TurretOffset=50
Image=SHAD
PrimaryFireFLH=175,0,10
ShadowIndex=2

[MEDUSA2]
SpawnDelay=2
Rotates=yes
Image=MEDUSA
UseLineTrail=yes
LineTrailColor=255,0,0
LineTrailColorDecrement=16

[MEDUSA3]
SpawnDelay=2
Rotates=yes
Image=MEDUSA
UseLineTrail=yes
LineTrailColorDecrement=16
LineTrailColor=255,185,65

[SAMMISSILE2] ; Sam Missile Remaked
Image=SUBT
UseLineTrail=yes
LineTrailColor=255,0,0
LineTrailColorDecrement=16
Rotates=yes
Voxel=yes

[NILS] ; By MoamenMagdy
CameoPCX=nilsicon.pcx
Voxel=yes
Image=TRNSPORT
Remapable=yes

[DRAGON2] ; Red DRAGON no linetrailcoloroverride
Image=DRAGON
UseLineTrail=yes
LineTrailColor=255,0,0
LineTrailColorDecrement=16
Rotates=yes

[DRAGON3] ; Golden DRAGON no linetrailcoloroverride
Image=DRAGON
UseLineTrail=yes
LineTrailColorDecrement=16
Rotates=yes
LineTrailColor=255,185,65

[CHAOSMACHINE] ; by MoamenMagdy
CameoPCX=chaosmachine.pcx
Voxel=yes
Image=MIND
Remapable=yes

[CPLANELT] ; don't use on buildable aircraft trail will overlap, use as spawned aircraft
Trailer=V3TRAIL
Image=cplane
Voxel=yes
PrimaryFireFLH=0,32,0
DisableVoxelCache=yes	; HY
DisableShadowCache=yes

[BEAGLT] ; Black Eagle remake of aircraft with a line trail
Voxel=no
Remapable=yes
UseLineTrail=yes
LineTrailColor=125,125,125
Image=BEAG
LineTrailColorDecrement=36
Cameo=BEAGICON
AltCameo=BEAGICON

[BPLNLT] ; Boris Attack Plane remake of aircraft with a line trail with dragon
Voxel=yes
Image=BPLN
UseLineTrail=yes
LineTrailColor=125,125,125
LineTrailColorDecrement=10
Remapable=yes
Cameo=BPLNICON
AltCameo=BPLNICON
PrimaryFireFLH=25,100,0

[FALCLT] ; Intruder remake of aircraft with a line trail with dragon
Voxel=yes
Remapable=yes
Cameo=FALCICON
Image=falc
UseLineTrail=yes
LineTrailColor=125,125,125
LineTrailColorDecrement=10
AltCameo=FALCUICO


