;-------------------------------------------------------------------------------------------------------------
; INI Control File for additional rulesmd entries for community maps.
; Any and all additions should only be used for custom maps. It should NEVER be noticeable or seen in vanilla.
; EVERYTHING, with 100% no exceptions, should have TechLevel=-1 **and** AIBuildThis=no.
;
; After making changes here and submitting them to the CNC-Net YR repository, please wait for approval.
;
; Try to keep this file clean and organized for future contributors.
;
; Created by the CNCNet community.
;-------------------------------------------------------------------------------------------------------------
;
;
; New vehicles, infantry or buildings should be listed within their appropriate type section with SUPER high numbers.
; YES, the game generates a new internal array at runtime so it could be CanCowsFly=Fuckyeah and it doesn't matter.
; BUT, we're gonna be 100% absolutely sure there's not gonna be any conflicts anywhere with custom maps.
;
; EXAMPLE BELOW
;
; [VehicleTypes]
; 50000=NewVehicleHere
; [InfantryTypes]
; 50000=NewInfantryHere
; [BuildingTypes]
; 50000=NewBuildingHere
