;-------------------------------------------------------------------------------------------------------------
; INI Control File for additional rulesmd entries for community maps.
; Any and all additions should only be used for custom maps. It should NEVER be noticeable or seen in vanilla.
; EVERYTHING, with 100% no exceptions, should have TechLevel=-1 **and** AIBuildThis=no.
;
; After making changes here and submitting them to the CNC-Net YR repository, please wait for approval.
;
; Try to keep this file clean and organized for future contributors.
;
; Created by the CNCNet community.
;-------------------------------------------------------------------------------------------------------------
;
;
; New vehicles, infantry or buildings should be listed within their appropriate type section with SUPER high numbers.
; YES, the game generates a new internal array at runtime so it could be CanCowsFly=Fuckyeah and it doesn't matter.
; BUT, we're gonna be 100% absolutely sure there's not gonna be any conflicts anywhere with custom maps.
;
; EXAMPLE BELOW
;
; [VehicleTypes]
; 50000=NewVehicleHere
; [InfantryTypes]
; 50000=NewInfantryHere
; [BuildingTypes]
; 50000=NewBuildingHere

[Animations]
50000=GATECH01_A
50001=GATECH01_AD

[BuildingTypes]
50000=CGBUNK05
50001=GATECH01

[CGBUNK05]; Bunker added by McPwny
UIName=NOSTR:Concrete Bunker
Name=Concrete Bunker
Adjacent=2
AIBasePlanningSide=1
Armor=steel
BaseNormal=no
BuildCat=Combat
Prerequisite=NACNST
Capturable=false
ClickRepairable=yes
Cost=500
Crewed=no
DebrisAnims=Dbris3sm,Dbris4lg,Dbris4sm,Dbris6sm,Dbris7lg,Dbris7sm,Dbris8sm,Dbris10lg,Dbris10sm
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
IsBaseDefense=yes
MaxDebris=15
MinDebris=5
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
Powered=no
Sight=6
Strength=600
TechLevel=-1
AIBuildThis=no
CanBeOccupied=yes
MaxNumberOccupants=5
CanOccupyFire=yes
AntiInfantryValue=25
AntiArmorValue=10
AntiAirValue=0

[GATECH01]; Allied battle lab remake by Volkov_T-666
UIName=Name:GATECH
Name=Allied Battle Lab
BuildCat=Tech
Prerequisite=GAWEAP,RADAR,GACNST
Strength=500
Armor=wood
TechLevel=-1
Adjacent=2
Sight=6
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
AIBasePlanningSide=0 ;gs 0 for Good, 1 for Evil
Cost=2000
Points=85
Power=-100
Capturable=true
Crewed=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DebrisAnims=DBRIS1LG,DBRIS1SM,DBRIS2LG,DBRIS4SM,DBRIS5LG,DBRIS5SM,DBRIS6SM,DBRS10LG
MaxDebris=12
MinDebris=6
ThreatPosed=0	; This value MUST be 0 for all building addons
;DamageParticleSystems=SparkSys,SmallGreySSys,BigGreySmokeSys
DamageSmokeOffset=1500, 1055, 815
AIBuildThis=no
TogglePower=no
Spyable=yes
ProtectWithWall=yes
ImmuneToPsionics=no ; defaults to yes for buildings, no for others
SuperWeapon=ForceShieldSpecial
