;-------------------------------------------------------------------------------------------------------------
; INI Control File for additional rulesmd entries for community maps.
; Any and all additions should only be used for custom maps. It should NEVER be noticeable or seen in vanilla.
; EVERYTHING, with 100% no exceptions, should have TechLevel=-1 **and** AIBuildThis=no.
;
; After making changes here and submitting them to the CNC-Net YR repository, please wait for approval.
;
; Try to keep this file clean and organized for future contributors.
;
; Created by the CNCNet community.
;-------------------------------------------------------------------------------------------------------------
;
;
; New vehicles, infantry or buildings should be listed within their appropriate type section with SUPER high numbers.
; YES, the game generates a new internal array at runtime so it could be CanCowsFly=Fuckyeah and it doesn't matter.
; BUT, we're gonna be 100% absolutely sure there's not gonna be any conflicts anywhere with custom maps.
;
; EXAMPLE BELOW
;
; [VehicleTypes]
; 50000=NewVehicleHere
; [InfantryTypes]
; 50000=NewInfantryHere
; [BuildingTypes]
; 50000=NewBuildingHere

[Animations]
50000=GATECH01_A
50001=GATECH01_AD
50002=NAGIGAT_G
50003=NAGIGAT_A
50004=NAGIGAT_AD
50005=NAGIGAT_SA
50006=NAGIGAT_SAD
50007=NAGIGAT_SB
50008=NAGIGAT_SBD
50009=NAGIGAT_SC
50010=NAGIGAT_SCD
50011=NAGIGAT_SD
50012=NAGIGAT_SDD
50013=PIFFPIFFW
50014=PIFFW
50015=FSStart
50016=FSEnd
50017=RAIN
50018=EMPBOLT1
50019=EMPBOLT2
50020=EMPBOLT3
50021=EMPBOLT4

[BuildingTypes]
50000=CGBUNK05
50001=GATECH01
50002=NAGIGAT

[VehicleTypes]
50000=NZEP
50001=KARGDRORPUS
50002=KAMRLEFRENA2

; Beginning of BuildingTypes

[CGBUNK05]; Bunker added by McPwny
UIName=NOSTR:Concrete Bunker
Name=Concrete Bunker
Adjacent=2
AIBasePlanningSide=1
Armor=steel
BaseNormal=no
BuildCat=Combat
Prerequisite=NACNST
Capturable=false
ClickRepairable=yes
Cost=500
Crewed=no
DebrisAnims=Dbris3sm,Dbris4lg,Dbris4sm,Dbris6sm,Dbris7lg,Dbris7sm,Dbris8sm,Dbrs10lg,Dbrs10sm
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
IsBaseDefense=yes
MaxDebris=15
MinDebris=5
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
Powered=no
Sight=6
Strength=600
TechLevel=-1
AIBuildThis=no
CanBeOccupied=yes
MaxNumberOccupants=5
CanOccupyFire=yes
AntiInfantryValue=25
AntiArmorValue=10
AntiAirValue=0

[GATECH01]; Allied battle lab remake by Volkov_T-666
UIName=Name:GATECH
Name=Allied Battle Lab
BuildCat=Tech
Prerequisite=GAWEAP,RADAR,GACNST
Strength=500
Armor=wood
TechLevel=-1
Adjacent=2
Sight=6
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
AIBasePlanningSide=0 ;gs 0 for Good, 1 for Evil
Cost=2000
Points=85
Power=-100
Capturable=true
Crewed=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DebrisAnims=DBRIS1LG,DBRIS1SM,DBRIS2LG,DBRIS4SM,DBRIS5LG,DBRIS5SM,DBRIS6SM,DBRS10LG
MaxDebris=12
MinDebris=6
ThreatPosed=0	; This value MUST be 0 for all building addons
;DamageParticleSystems=SparkSys,SmallGreySSys,BigGreySmokeSys
DamageSmokeOffset=1500, 1055, 815
AIBuildThis=no
TogglePower=no
Spyable=yes
ProtectWithWall=yes
ImmuneToPsionics=no ; defaults to yes for buildings, no for others
SuperWeapon=ForceShieldSpecial

[NAGIGAT]; Soviet tesla structure by McPwny
UIName=NOSTR:Giga Chad Tesla Coil
Name=Soviet Tesla thing
BuildCat=Power
Prerequisite=NACNST
Strength=3000
Armor=concrete
TechLevel=-1
Sight=4
Adjacent=2
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
AIBasePlanningSide=1
Cost=600
Points=40
Power=150
Capturable=true
Crewed=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60,tstlexp
MaxDebris=15
MinDebris=5
DebrisAnims=DBRIS1LG,DBRIS1SM,DBRIS4LG,DBRIS4SM,DBRIS5LG,DBRIS5SM
ThreatPosed=5
DamageParticleSystems=SparkSys,SmallGreySSys,BigGreySmokeSys
DamageSmokeOffset=450, 200, 300
TogglePower=no
Spyable=yes
DieSound=PowerPlantDie
ImmuneToPsionics=yes
Drainable=no
PoweredSpecial=yes
AntiInfantryValue=25
AntiArmorValue=25
AntiAirValue=25
AIBuildThis=no
SuperWeapon=LightningStormSpecial
ChargedAnimTime=1
CanBeOccupied=yes
MaxNumberOccupants=6
CanOccupyFire=yes

; End of BuildingTypes
; Beginning of VehicleTypes

[NZEP]; New Kirov Airship uploaded by MoamenMagdy
UIName=NOSTR:Blimp The Plumber
Name=Kirov Airship
Prerequisite=NAWEAP,NATECH
Primary=BlimpBomb
Strength=2000
Category=AirPower
Armor=medium
TechLevel=-1
Sight=8
RadarInvisible=no
MoveToShroud=yes
BalloonHover=yes
Speed=5
JumpjetSpeed=5
JumpjetClimb=6
JumpjetCrash=12
JumpJetAccel=10
JumpJetTurnRate=2
JumpjetHeight=750
JumpjetNoWobbles=yes
Crashable=yes
PitchSpeed=.9
PitchAngle=0
Owner=Russians,Confederation,Africans,Arabs
Cost=2000
Soylent=2000
Points=100
ROT=10
SpeedType=Hover
Crewed=no
ConsideredAircraft=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=14
IsSelectableCombatant=yes
VoiceSelect=KirovSelect
VoiceMove=KirovMove
VoiceAttack=KirovAttackCommand
VoiceFeedback=
VoiceCrashing=KirovVoiceDie
DieSound=
CreateSound=KirovCreated
CrashingSound=KirovDie
ImpactLandSound=KirovCrash
Locomotor={92612C46-F71F-11d1-AC9F-006008055BB5}
MovementZone=Fly
ThreatPosed=30
DamageParticleSystems=SparkSys,SmallGreySSys
AuxSound1=Dummy
AuxSound2=Dummy
AllowedToStartInMultiplayer=no
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
SelfHealing=Yes
MoveSound=KirovMoveLoop
ElitePrimary=BlimpBombE
Parasiteable=no
Size=50
Bunkerable=no

[KARGDRORPUS]; By CustomDimensional=yes (in modhaven), uploaded by MoamenMagdy
ROT=5
Cost=1400
Name=Missile Gunship
Size=15
Armor=light
Owner=Russians,Confederation,Africans,Arabs
Sight=7
Speed=12
Crewed=no
Points=15
Turret=yes
UIName=NOSTR:Missile Gunship
JumpJet=yes
Primary=Medusa
Soylent=1400
Category=AirPower
DieSound=
Strength=2500
Crashable=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
Locomotor={92612C46-F71F-11d1-AC9F-006008055BB5}
MaxDebris=3
MoveSound=SeigeChopperMoveLoop
SizeLimit=2
SpeedType=Hover
TechLevel=-1
Trainable=yes
VoiceMove=SeigeChopperMove
Bunkerable=no
PitchSpeed=1.1
HoverAttack=yes
ThreatPosed=0
VoiceAttack=SeigeChopperAttackAir
VoiceSelect=SeigeChopperSelect
ElitePrimary=Medusa
JumpJetAccel=12
JumpjetClimb=10
JumpjetCrash=40
JumpjetSpeed=30
MovementZone=Fly
Prerequisite=NAWEAP
CrashingSound=SeigeChopperDie
JumpjetHeight=500
VoiceCrashing=SeigeChopperVoiceDie
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
JumpjetWobbles=.01
UnloadingClass=SCHD
ImpactLandSound=GenAircraftCrash
JumpJetTurnRate=6
JumpjetDeviation=1
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
PreventAttackMove=yes
ConsideredAircraft=yes
SpecialThreatValue=1
EnterTransportSound=EnterTransport
LeaveTransportSound=ExitTransport
DamageParticleSystems=SparkSys,SmallGreySSys
IsSelectableCombatant=yes
TooBigToFitUnderBridge=true
AllowedToStartInMultiplayer=no

[KAMRLEFRENA2]; By CustomDimensional=yes (in modhaven), uploaded by MoamenMagdy
ROT=5
Cost=1400
Name=The Soviet Power Supreme!!! {T_T}
Size=15
Armor=light
Owner=Russians,Confederation,Africans,Arabs
Sight=7
Speed=12
Crewed=no
Points=15
Turret=yes
UIName=NOSTR:Tesla Ultimateship
AirRate=2
JumpJet=yes
Primary=TankBolt
Soylent=1400
Category=AirPower
DieSound=
IdleRate=3
Strength=30000
Crashable=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
Locomotor={92612C46-F71F-11d1-AC9F-006008055BB5}
MaxDebris=3
MoveSound=SeigeChopperMoveLoop
SizeLimit=2
SpeedType=Hover
TechLevel=-1
Trainable=yes
VoiceMove=SeigeChopperMove
Bunkerable=no
OpenTopped=yes
Passengers=4
PitchSpeed=1.1
FlightLevel=5000
ThreatPosed=0
VoiceAttack=SeigeChopperAttackAir
VoiceSelect=SeigeChopperSelect
BalloonHover=yes
JumpJetAccel=12
JumpjetClimb=10
JumpjetCrash=40
JumpjetSpeed=30
MovementZone=Fly
NoManualLoad=yes
Prerequisite=NAWEAP
CrashingSound=SeigeChopperDie
JumpjetHeight=1000
VoiceCrashing=SeigeChopperVoiceDie
JumpjetWobbles=.01
NoManualUnload=yes
ImpactLandSound=GenAircraftCrash
JumpJetTurnRate=6
SelfHealing.Max=25%
JumpjetDeviation=1
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
ConsideredAircraft=yes
SelfHealing.Amount=15
SpecialThreatValue=1
EnterTransportSound=EnterTransport
LeaveTransportSound=ExitTransport
DamageParticleSystems=SparkSys,SmallGreySSys
IsSelectableCombatant=yes
TooBigToFitUnderBridge=true
AllowedToStartInMultiplayer=no
