[VersionInfo]
Name=Red Alert 2 (CnCnet)
Version=1.006

[AdvancedCommandBar]
ButtonList=Team01,Team02,TypeSelect,Deploy,Guard,PlanningMode

[MultiplayerAdvancedCommandBar]
ButtonList=Team01,Team02,TypeSelect,Deploy,Guard,PlanningMode,Beacon

[Sidebar]
CenterPauseMenuBackground=yes
HarvesterCounter.Show=yes
HarvesterCounter.ConditionYellow=99%
HarvesterCounter.ConditionRed=50%
PowerDelta.Show=yes
PowerDelta.ConditionYellow=75%
PowerDelta.ConditionRed=100%

[ToolTips]
ExtendedToolTips=yes

; New Ares section
[Colors]; selection box colors
Count=16; max 16!

Observer.DisplayColor=96,96,96
Observer.ColorScheme=LightGrey

Slot1.DisplayColor=222,227,8
Slot1.ColorScheme=Gold

Slot2.DisplayColor=255,0,0
Slot2.ColorScheme=DarkRed

Slot3.DisplayColor=41,115,231
Slot3.ColorScheme=DarkBlue

Slot4.DisplayColor=119,190,38
Slot4.ColorScheme=DarkGreen

Slot5.DisplayColor=255,165,24
Slot5.ColorScheme=Orange

Slot6.DisplayColor=49,214,231
Slot6.ColorScheme=DarkSky

Slot7.DisplayColor=148,41,189
Slot7.ColorScheme=Purple

Slot8.DisplayColor=255,156,239
Slot8.ColorScheme=Magenta

Slot9.DisplayColor=200,170,140
Slot9.ColorScheme=Camel

Slot10.DisplayColor=180,10,90
Slot10.ColorScheme=Crimson

Slot11.DisplayColor=0,128,128
Slot11.ColorScheme=Teal

Slot12.DisplayColor=180,250,40
Slot12.ColorScheme=Pistachio

Slot13.DisplayColor=150,85,30
Slot13.ColorScheme=Brown

Slot14.DisplayColor=180,255,220
Slot14.ColorScheme=Mint

Slot15.DisplayColor=250,25,250
Slot15.ColorScheme=NewMagenta

Slot16.DisplayColor=190,160,255
Slot16.ColorScheme=Periwinkle
