[TextShaping]
Enabled=true		; Shaping enabled. More performance intensive, but has letters laid out correctly
EnableBiDi=true		; Enable bidirectional text support (mixed LTR/RTL) for Arabic text
CacheSize=100		; Number of shaped text entries to cache. Higher values use more memory but improve performance


[Fonts]
Count=3

;main text - chat messages, etc
[Font0]
Type=TrueType
Size=12
Path=\Fonts\Roboto-SemiBold.ttf
Fallback=2

;buttons, dropdowns, etc
[Font1]
Type=TrueType
Size=13
Path=\Fonts\Roboto-SemiBold.ttf
Fallback=2

;Allow emojis
[Font2]
Type=TrueType
Size=12
Path=\Fonts\NotoEmoji-SemiBold.ttf
