; The Dawn of the Tiberium Age (DTA) CnCNet Client settings
; Created by Rampastring
; http://www.moddb.com/members/rampastring
; If you use or redistribute the client in any public projects, please include
; Rampastring and The Dawn of the Tiberium Age in your project's credits.

[General]
Sides=America,Korea,France,Germany,Great Britain,Libya,Iraq,Cuba,Russia,Yuri
StartingLocationAngularVelocity=0.01
ReservedStartingLocationAngularVelocity=0.01
SpectatorInternalSideIndex=-3

[RandomSelectors]
Allied=0,1,2,3,4
Soviet=5,6,7,8
Ladder=0,1,2,4,6,6,6,6,9,9,9,9

; The 8 multiplayer colors. Syntax: <Name>=R,G,B,<in-game color ID>
[MPColors]
Yellow=230,220,13,0
Red=255,25,25,1
Blue=34,107,212,2
Green=61,210,45,3
Orange=255,160,25,4
Light Blue=49,217,230,5
Purple=146,40,189,6
Pink=255,153,237,7

; Defines settings that are used in the CnCNet Game Lobby UI.
[MultiplayerGameLobby]
SharpenImages=no
DefaultWindowSize=1180x702
PlayerReadyBoxY=2
PlayerReadyBoxX=6
PlayerOptionLocationX=29
PlayerOptionLocationY=25
PlayerOptionVerticalMargin=9
PlayerOptionHorizontalMargin=5
PlayerOptionCaptionLocationY=6
PlayerNameWidth=120
SideWidth=155
ColorWidth=85
StartWidth=45
TeamWidth=35

; Defines settings that are used in the Skirmish Game Lobby UI.
[SkirmishLobby]
SharpenImages=no
DefaultWindowSize=1180x702
PlayerOptionLocationX=12
PlayerOptionLocationY=25
PlayerOptionVerticalMargin=9
PlayerOptionHorizontalMargin=5
PlayerOptionCaptionLocationY=6
PlayerNameWidth=120
SideWidth=155
ColorWidth=85
StartWidth=50
TeamWidth=45

; Keys that are ALWAYS written to spawn.ini when the game starts.
; These can be overriden by gamemode-specific code.
[ForcedSpawnIniOptions]
Bases=Yes
FogOfWar=No
SidebarHack=Yes
AttackNeutralUnits=yes
ReconnectTimeout=1400
Protocol=0
FrameSendRate=2
Crates=True
Superweapons=False