[INISystem]
BasedOn=GenericWindow.ini

[GameLobbyBase]
PlayerStatusIndicatorX=2
PlayerStatusIndicatorY=0
PlayerReadyBoxX=1
PlayerReadyBoxY=2
PlayerOptionLocationX=25
PlayerOptionLocationY=25
PlayerOptionVerticalMargin=7
PlayerOptionHorizontalMargin=2
PlayerOptionCaptionLocationY=6
PlayerNameWidth=90
SideWidth=120
ColorWidth=80
StartWidth=40
TeamWidth=35

; controls
$CC00=btnLaunchGame:GameLaunchButton
$CC01=btnLeaveGame:XNAClientButton
$CC03=MapPreviewBox:MapPreviewBox
$CC04=GameOptionsPanel:XNAPanel
$CC05=PlayerOptionsPanel:XNAPanel
$CC06=lblMapName:XNALabel
$CC07=lblMapAuthor:XNALabel
$CC08=lblGameMode:XNALabel
$CC09=lblMapSize:XNALabel
$CC12=lbMapList:XNAMultiColumnListBox
$CC13=ddGameMode:XNAClientDropDown
$CC14=lblGameModeSelect:XNALabel
$CC15=btnPickRandomMap:XNAClientButton
$CC16=tbMapSearch:XNASuggestionTextBox
$CC17=PlayerExtraOptionsPanel:PlayerExtraOptionsPanel
$CC18=lbChatMessages:ChatListBox
$CC19=tbChatInput:XNAChatTextBox
$CC20=btnCnCNet:XNALinkButton
$CC21=chkAutoSave:GameLobbyCheckBox
$CC22=ractl:XNAExtraPanel
$CC23=ractr:XNAExtraPanel
$CC24=racbl:XNAExtraPanel
$CC25=racbr:XNAExtraPanel
$CC26=rabt:XNAExtraPanel
$CC27=rabb:XNAExtraPanel
$CC28=rabl:XNAExtraPanel
$CC29=rabr:XNAExtraPanel
$CC30=btnPhobos:XNALinkButton
$CC31=btnAres:XNALinkButton

[lblName]
Text=Players

[lblSide]
Text=Side

[lblColor]
Text=Color

[lblTeam]
Text=Team

[lblStart]
Text=Start
Visible=true

[ddPlayerStartBase]
Enabled=true
Visible=true

[ddPlayerStart0]
$BaseSection=ddPlayerStartBase

[ddPlayerStart1]
$BaseSection=ddPlayerStartBase

[ddPlayerStart2]
$BaseSection=ddPlayerStartBase

[ddPlayerStart3]
$BaseSection=ddPlayerStartBase

[ddPlayerStart4]
$BaseSection=ddPlayerStartBase

[ddPlayerStart5]
$BaseSection=ddPlayerStartBase

[ddPlayerStart6]
$BaseSection=ddPlayerStartBase

[ddPlayerStart7]
$BaseSection=ddPlayerStartBase

[ddPlayerColorBase]
RandomColorTexture=randomcolor.png
ItemsDrawMode=TextAndIcon
ColorTextureHeight=16
ColorTextureWidth=18

[ddPlayerColor0]
$BaseSection=ddPlayerColorBase

[ddPlayerColor1]
$BaseSection=ddPlayerColorBase

[ddPlayerColor2]
$BaseSection=ddPlayerColorBase

[ddPlayerColor3]
$BaseSection=ddPlayerColorBase

[ddPlayerColor4]
$BaseSection=ddPlayerColorBase

[ddPlayerColor5]
$BaseSection=ddPlayerColorBase

[ddPlayerColor6]
$BaseSection=ddPlayerColorBase

[ddPlayerColor7]
$BaseSection=ddPlayerColorBase

[lbMapList]
$X=LOBBY_EMPTY_SPACE_SIDES
$Y=EMPTY_SPACE_TOP + 33
$Width=getWidth($ParentControl) - (getX($Self) + (getWidth(MapPreviewBox) + LOBBY_EMPTY_SPACE_SIDES + LOBBY_PANEL_SPACING))
$Height=getBottom(MapPreviewBox) - getY($Self)
SolidColorBackgroundTexture=0,0,0,200

[ddGameMode]
$Width=180
$Height=DEFAULT_CONTROL_HEIGHT
$X=getRight(lbMapList) - getWidth($Self)
$Y=getY(lbMapList) - getHeight($Self) - EMPTY_SPACE_TOP

[lblGameModeSelect]
Text=GAME MODE:
$X=getX(ddGameMode) - getWidth($Self) - 35
$Y=getY(ddGameMode) + 1

[btnMapSortAlphabetically]
Visible=true
Enabled=true

[btnLaunchGame]
Text=Launch Game
$Width=BUTTON_WIDTH_133
$Height=DEFAULT_BUTTON_HEIGHT
$X=LOBBY_EMPTY_SPACE_SIDES
$Y=getHeight($ParentControl) - getHeight($Self) - EMPTY_SPACE_BOTTOM
ClickSoundEffect=button.wav

[chkAutoSave]
Text=Auto Save
SpawnIniOption=AutoSaveInterval
DataWriteMode=String
EnabledSpawnIniValue=7200
DisabledSpawnIniValue=0
Checked=false
$X=getRight(btnLaunchGame) + 150
$Y=getY(btnLaunchGame) + 2
Enabled=true
Visible=true
ToolTip=Auto saves the game every 2 minutes at 60 FPS.

[btnPickRandomMap]
Text=Pick Random Map
$Width=BUTTON_WIDTH_133
$Height=DEFAULT_BUTTON_HEIGHT
$X=getRight(btnLaunchGame) + LOBBY_PANEL_SPACING
$Y=getY(btnLaunchGame)

[tbMapSearch]
Suggestion=Search map...
BackColor=255,255,255
$Width=getWidth(lbMapList)
$Height=DEFAULT_CONTROL_HEIGHT
$X=LOBBY_EMPTY_SPACE_SIDES
$Y=getBottom(MapPreviewBox) + LOBBY_PANEL_SPACING

[lbChatMessagesBase]
SolidColorBackgroundTexture=0,0,0,200
$Width=getWidth(lbMapList)
$X=LOBBY_EMPTY_SPACE_SIDES

[MapPreviewBox]
$Width=825
$Height=getHeight($ParentControl) - getY($Self) - 380
$X=getWidth($ParentControl) - getWidth($Self) - LOBBY_EMPTY_SPACE_SIDES
$Y=285
SolidColorBackgroundTexture=0,0,0,200

[lblMapName]
$Height=DEFAULT_LBL_HEIGHT
$X=getX(MapPreviewBox)
$Y=getBottom(MapPreviewBox) + LABEL_SPACING

[lblMapAuthor]
$TextAnchor=LEFT
$AnchorPoint=getRight(MapPreviewBox),getY(lblMapName)

[lblGameMode]
$Height=DEFAULT_LBL_HEIGHT
$X=getX(lblMapName)
$Y=getBottom(lblMapName) + LABEL_SPACING

[lblMapSize]
$TextAnchor=LEFT
$AnchorPoint=getRight(MapPreviewBox),getY(lblMapName) + 18
$Height=DEFAULT_LBL_HEIGHT
$X=getX(lblMapAuthor)
$Y=getBottom(lblMapAuthor)

[PlayerOptionsPanel]
$X=getX(MapPreviewBox)
$Y=EMPTY_SPACE_TOP
$Width=getWidth($ParentControl) - (getX($Self) + (getWidth(GameOptionsPanel) + LOBBY_EMPTY_SPACE_SIDES + LOBBY_PANEL_SPACING - 8))
$Height=getHeight(GameOptionsPanel)
SolidColorBackgroundTexture=0,0,0,200
$CC00=btnPlayerExtraOptionsOpen:XNAClientButton

[PlayerExtraOptionsPanel]
$Width=238
$Height=247
$X=getRight(PlayerOptionsPanel) - getWidth($Self)
$Y=getY(PlayerOptionsPanel)

[btnPlayerExtraOptionsOpen]
$Width=BTN_MENU_OPEN_WIDTH
$Height=BTN_MENU_OPEN_HEIGHT
Enabled=true
Visible=true
IdleTexture=optionsButton.png
HoverTexture=optionsButton_c.png

[GameOptionsPanel]
$Width=420
$Height=260
$X=getWidth($ParentControl) - getWidth($Self) - LOBBY_EMPTY_SPACE_SIDES
$Y=EMPTY_SPACE_TOP
SolidColorBackgroundTexture=0,0,0,200

; Left column
$CC-GO01=chkShortGame:GameLobbyCheckBox
$CC-GO02=chkRedeplMCV:GameLobbyCheckBox
$CC-GO03=chkAutoRepair:GameLobbyCheckBox
$CC-GO04=chkMultiEng:GameLobbyCheckBox
$CC-GO05=chkIngameAllying:GameLobbyCheckBox

; Middle column
$CC-GO06=chkDestrBridges:GameLobbyCheckBox
$CC-GO07=chkBuildOffAlly:GameLobbyCheckBox
$CC-GO08=chkRA2Mode:GameLobbyCheckBox
$CC-GO09=chkBalancePatch:GameLobbyCheckBox
$CC-GO10=chkNoSpawnPreviews:GameLobbyCheckBox
$CC-GO11=chkDisableGameSpeed:GameLobbyCheckBox

; Right column
$CC-GO12=chkNoYuri:GameLobbyCheckBox
$CC-GO13=chkNoFrance:GameLobbyCheckBox
$CC-GO14=chkNoSpy:GameLobbyCheckBox
$CC-GO15=chkNoStolenTech:GameLobbyCheckBox
$CC-GO16=chkNoDogEngiEat:GameLobbyCheckBox
$CC-GO17=chkCrates:GameLobbyCheckBox

; Drop Down Controls
$CC-GO18=lblCredits:XNALabel
$CC-GO19=cmbCredits:GameLobbyDropDown
$CC-GO20=lblStartingUnits:XNALabel
$CC-GO21=cmbStartingUnits:GameLobbyDropDown
$CC-GO22=lblSuperWeapons:XNALabel
$CC-GO23=cmbSuperWeaponsModifier:GameLobbyDropDown
$CC-GO24=lblCratesModifier:XNALabel
$CC-GO25=cmbCratesModifier:GameLobbyDropDown
$CC-GO26=lblAIModifier:XNALabel
$CC-GO27=cmbAIModifier:GameLobbyDropDown

; New FPS Sliders
$CC-GODD03PH=cmbGameSpeedCapPlaceholder:XNAControl
$CC-GODD04=lblGameSpeedCap:XNALabel

; Save / Load Game Options lul
$CC-G099=btnSaveLoadGameOptions:XNAClientButton

;============================
; LEFT Column Controls
;============================

[chkShortGame]
Text=Short Game
SpawnIniOption=ShortGame
Checked=True
ToolTip=Players win when all enemy buildings are destroyed.
$X=EMPTY_SPACE_SIDES
$Y=EMPTY_SPACE_TOP

[chkRedeplMCV]
Text=MCV Repacks
SpawnIniOption=MCVRedeploy
Checked=True
ToolTip=Players have the ability to move their command center after it's deployed.
$X=getX(chkShortGame)
$Y=getBottom(chkShortGame) + GAME_OPTION_ROW_SPACING

[chkAutoRepair]
Text=Auto Repair
CustomIniPath=INI\Game Options\Auto Repair.ini
Checked=False
ToolTip=Buildings will automatically repair themselves.
$X=getX(chkShortGame)
$Y=getBottom(chkRedeplMCV) + GAME_OPTION_ROW_SPACING

[chkMultiEng]
SpawnIniOption=MultiEngineer
Checked=False
ToolTip=Capturing a structure requires three Engineers instead of one.
Text=Multi Engineer
$X=getX(chkShortGame)
$Y=getBottom(chkAutoRepair) + GAME_OPTION_ROW_SPACING

[chkIngameAllying]
Text=Ingame Allying
SpawnIniOption=AlliesAllowed
CustomIniPath=INI\Game Options\Allies Allowed.ini
Checked=True
ToolTip=Players can form and break alliances in game.
$X=getX(chkShortGame)
$Y=getBottom(chkMultiEng) + GAME_OPTION_ROW_SPACING

;============================
; Middle Column Controls
;============================

[chkDestrBridges]
SpawnIniOption=BridgeDestroy
Checked=True
ToolTip=You can destroy low bridges by force-firing on them.
Text=Destroyable Bridges
$X=getX(chkShortGame) + 135
$Y=EMPTY_SPACE_TOP

[chkBuildOffAlly]
SpawnIniOption=BuildOffAlly
Checked=True
ToolTip=Check to allow players to build near their allies' construction yards.
Text=Build By Ally
$X=getX(chkDestrBridges)
$Y=getBottom(chkDestrBridges) + GAME_OPTION_ROW_SPACING

[chkRA2Mode]
SpawnIniOption=Ra2Mode
DefaultValue=False
ToolTip=Red Alert 2 Classic Mode will turn gameplay into Red Alert 2.
Text=Red Alert 2
DisallowedSideIndex=9
$X=getX(chkDestrBridges)
$Y=getBottom(chkBuildOffAlly) + GAME_OPTION_ROW_SPACING

[chkBalancePatch]
CustomIniPath=INI\Game Options\Yuri Rebalance Patch.ini
DefaultValue=False
ToolTip=Yuri's Revenge Rebalance 2.0@Patch notes: https://forums.cncnet.org/topic/11738-yuris-revenge-rebalanced-20/
Text=YR Rebalance
$X=getX(chkDestrBridges)
$Y=getBottom(chkRA2Mode) + GAME_OPTION_ROW_SPACING

[chkNoSpawnPreviews]
CustomIniPath=INI\Game Options\No Spawn Previews.ini
DefaultValue=False
ToolTip=Start locations for players won't be shown in the loading screen.
Text=Blind Start
$X=getX(chkDestrBridges)
$Y=getBottom(chkBalancePatch) + GAME_OPTION_ROW_SPACING

[chkDisableGameSpeed]
SpawnIniOption=DisableGameSpeed
DefaultValue=False
ToolTip=Disable game speed adjustment in game.
Text=Lock Game Speed
$X=getX(chkDestrBridges)
$Y=getBottom(chkNoSpawnPreviews) + GAME_OPTION_ROW_SPACING

;============================
; Right Column Controls
;============================

[chkNoYuri]
CustomIniPath=INI\Game Options\No_Yuri.ini
DefaultValue=False
ToolTip=Yuri is disabled
Text=No Yuri
DisallowedSideIndices=9
$X=getX(chkShortGame) + 275
$Y=EMPTY_SPACE_TOP

[chkNoFrance]
CustomIniPath=INI\Game Options\No_France.ini
DefaultValue=False
ToolTip=France is disabled
Text=No France
DisallowedSideIndices=2
$X=getX(chkNoYuri)
$Y=getBottom(chkNoYuri) + GAME_OPTION_ROW_SPACING

[chkNoSpy]
CustomIniPath=INI\Game Options\No_Spy.ini
DefaultValue=False
ToolTip=Spies are disabled
Text=No Spy
$X=getX(chkNoYuri)
$Y=getBottom(chkNoFrance) + GAME_OPTION_ROW_SPACING

[chkNoStolenTech]
CustomIniPath=INI\Game Options\No Stolen Tech.ini
Checked=False
ToolTip=Stolen Tech is disabled
Text=No Stolen Tech
DataWriteMode=MapCode
$X=getX(chkNoYuri)
$Y=getBottom(chkNoSpy) + GAME_OPTION_ROW_SPACING

[chkNoDogEngiEat]
CustomIniPath=INI\Game Options\No Dog Engi Eat.ini
Checked=False
ToolTip=Dogs will be unable to kill Engineers.
Text=Engi Dog Immune
$X=getX(chkNoYuri)
$Y=getBottom(chkNoStolenTech) + GAME_OPTION_ROW_SPACING

[chkCrates]
SpawnIniOption=Crates
Checked=False
ToolTip=Random Power-Up Crates will appear.
Text=Crates Appear
$X=getX(chkNoYuri)
$Y=getBottom(chkNoDogEngiEat) + GAME_OPTION_ROW_SPACING

;============================
; Drop Down Controls
;============================

[lblGameSpeedCap]
Text=Game Speed:
$Height=DEFAULT_LBL_HEIGHT
$X=getX(chkShortGame)
$Y=getBottom(chkIngameAllying) + 30

[cmbGameSpeedCap]
OptionName=Game Speed
DefaultIndex=0
SpawnIniOption=GameSpeed
DataWriteMode=Index
ToolTip=Sets Maximum FPS
$Width=getWidth(cmbGameSpeedCapPlaceholder)
$Height=getHeight(cmbGameSpeedCapPlaceholder)
$X=getX(chkShortGame)
$Y=getBottom(lblGameSpeedCap) + 6

[cmbGameSpeedCapPlaceholder]
Visible=false
Enabled=false
$Width=112
$Height=DEFAULT_CONTROL_HEIGHT
$X=getX(cmbCredits)
$Y=getY(lblCredits)

[lblCredits]
Text=Credits:
$Height=DEFAULT_LBL_HEIGHT
$X=getX(chkIngameAllying)
$Y=getBottom(chkIngameAllying) + 72

[cmbCredits]
OptionName=Starting Credits
Items=100000,30000,20000,15000,12500,10000,7500,5000,2500
DefaultIndex=5
SpawnIniOption=Credits
DataWriteMode=String
ToolTip=Credits at the start of the game.
$Width=112
$Height=GAME_OPTION_DD_HEIGHT
$X=getX(lblCredits)
$Y=getBottom(lblCredits) + GAME_OPTION_ROW_SPACING

[lblStartingUnits]
Text=Starting Units:
$Height=DEFAULT_LBL_HEIGHT
$X=getX(chkDestrBridges)
$Y=getBottom(chkNoSpawnPreviews) + 30

[cmbStartingUnits]
OptionName=Starting Units
ToolTip=Starting Units at the beginning of the game.
Items=10,9,8,7,6,5,4,3,2,1,0
DefaultIndex=10
SpawnIniOption=UnitCount
DataWriteMode=String
DistanceFromRightBorder=51
$X=getX(lblStartingUnits)
$Y=getBottom(lblStartingUnits) + GAME_OPTION_ROW_SPACING
$Width=112
$Height=DEFAULT_CONTROL_HEIGHT

[lblSuperWeapons]
Text=Super Weapons:
$Height=DEFAULT_LBL_HEIGHT
$X=getX(chkDestrBridges)
$Y=getBottom(cmbStartingUnits) + GAME_OPTION_GAP

[cmbSuperWeaponsModifier]
OptionName=SuperWeapon Settings:
Items=INI\Game Options\SuperWeapons\All.ini,INI\Game Options\SuperWeapons\Offensive.ini,INI\Game Options\SuperWeapons\Defensive.ini,INI\Game Options\SuperWeapons\Disabled.ini
DefaultIndex=0
SpawnIniOption=String
DataWriteMode=MapCode
ToolTip=Super Weapons Settings
ItemLabels=Enabled,Offensive,Defensive,Disabled
$X=getX(lblSuperWeapons)
$Y=getBottom(lblSuperWeapons) + 6
$Width=112
$Height=DEFAULT_CONTROL_HEIGHT

[lblCratesModifier]
Text=Crate Frequency:
$Height=DEFAULT_LBL_HEIGHT
$X=getX(chkNoDogEngiEat)
$Y=getBottom(chkCrates) + GAME_OPTION_GAP + 3

[cmbCratesModifier]
OptionName=Crate Frequency:
Items=INI\Game Options\Crates\Minimal.ini,INI\Game Options\Crates\Normal.ini,INI\Game Options\Crates\Increased.ini,INI\Game Options\Crates\Extreme.ini
DefaultIndex=1
SpawnIniOption=String
DataWriteMode=MapCode
ToolTip=Adjust the number of crates. This setting is pointless without Crate check box Enabled.
ItemLabels=Minimal Crates,Normal Crates,Increased Crates,Extreme Crates
$Width=112
$Height=GAME_OPTION_DD_HEIGHT
$X=getX(lblCratesModifier)
$Y=getBottom(lblCratesModifier) + GAME_OPTION_ROW_SPACING

[lblAIModifier]
Text=AI Modifier:
$Height=DEFAULT_LBL_HEIGHT
$X=getX(chkNoYuri)
$Y=getBottom(cmbCratesModifier) + GAME_OPTION_GAP

[cmbAIModifier]
OptionName=AI Modifier:
Items=INI\Game Options\AI\No Change.ini,INI\Game Options\AI\Brutal AI.ini,INI\Game Options\AI\Extreme AI.ini,INI\Game Options\AI\Extreme AI Beta.ini
DefaultIndex=0
SpawnIniOption=String
DataWriteMode=MapCode
ToolTip=Set the behaviour of the Computer AI.
ItemLabels=Vanilla AI,Brutal AI,Extreme AI,Extreme AI Beta
$X=getX(lblAIModifier)
$Y=getBottom(lblAIModifier) + 6
$Width=112
$Height=DEFAULT_CONTROL_HEIGHT

;============================
; End of Controls
;============================

[btnSaveLoadGameOptions]
$Width=BTN_MENU_OPEN_WIDTH
$Height=BTN_MENU_OPEN_WIDTH
Location=0,0
DistanceFromRightBorder=0
IdleTexture=comboBoxArrow.png
HoverTexture=comboBoxArrow.png

[btnLeaveGame]
Text=Leave Game
$Width=BUTTON_WIDTH_133
$Height=DEFAULT_BUTTON_HEIGHT
$X=getWidth($ParentControl) - getWidth($Self) - LOBBY_EMPTY_SPACE_SIDES
$Y=getY(btnLaunchGame)

[btnCnCNet]
Location=0,0
Size=133,23
IdleTexture=logo.png
HoverTexture=logo.png
DrawMode=Stretched
DrawBorders=false
URL=https://cncnet.org/red-alert-2
ToolTip=CnCNet - Red Alert 2 & Yuri's Revenge Online
$X=getX(lblMapName)
$Y=getHeight($ParentControl) - getHeight($Self) - EMPTY_SPACE_BOTTOM

[btnPhobos]
Size=73,23
IdleTexture=logo-2.png
HoverTexture=logo-2.png
DrawMode=Stretched
DrawBorders=false
URL=https://phobos.readthedocs.io/en/v0.4/index.html
ToolTip=Ares-compatible C&C Red Alert 2: Yuri's Revenge engine extension@@Version: 0.4
$X=getRight(btnCnCNet) + EMPTY_SPACE_SIDES
$Y=getY(btnCnCNet)

[btnAres]
Size=32,23
IdleTexture=logo-3.png
HoverTexture=logo-3.png
DrawMode=Stretched
DrawBorders=false
URL=https://ares-developers.github.io/Ares-docs/
ToolTip=Ares is the next generation of binary-based Command & Conquer modding@@Version: 3.0p1
$X=getRight(btnPhobos) + EMPTY_SPACE_SIDES
$Y=getY(btnPhobos)

;Sides

[rabt]
Location=0,-8
BackgroundTexture=rabt.png
DrawMode=Stretched
Size=0,9
FillWidth=0

[rabb]
Location=0,999
BackgroundTexture=rabb.png
DrawMode=Stretched
Size=0,9
FillWidth=0
DistanceFromBottomBorder=-8

[rabl]
Location=-8,0
BackgroundTexture=rabl.png
DrawMode=Stretched
Size=9,0
FillHeight=0

[rabr]
Location=999,0
BackgroundTexture=rabr.png
DrawMode=Stretched
Size=9,0
FillHeight=0
DistanceFromRightBorder=-8

;Corners

[ractl]
Location=-8,-8
BackgroundTexture=ractl.png
Size=9,9

[ractr]
Location=999,-8
BackgroundTexture=ractr.png
Size=9,9
DistanceFromRightBorder=-8

[racbl]
Location=-8,999
BackgroundTexture=racbl.png
Size=9,9
DistanceFromBottomBorder=-8

[racbr]
Location=999,999
BackgroundTexture=racbr.png
Size=9,9
DistanceFromRightBorder=-8
DistanceFromBottomBorder=-8
