[INISystem]
BasedOn=GenericWindow.ini

[GameLobbyBase]
;$BaseSection=FullWindow
PlayerReadyBoxY=2
PlayerReadyBoxX=2
PlayerOptionLocationX=22                ;10
PlayerOptionLocationY=25
PlayerOptionVerticalMargin=7
PlayerOptionHorizontalMargin=2
PlayerOptionCaptionLocationY=6
PlayerNameWidth=102                     ;132
SideWidth=120                           ;106
ColorWidth=76                           ;70
StartWidth=32                           ;36   
TeamWidth=32                            ;36

; controls
$CC00=btnLaunchGame:GameLaunchButton
$CC01=btnLeaveGame:XNAClientButton
$CC03=MapPreviewBox:MapPreviewBox
$CC04=GameOptionsPanel:XNAPanel
$CC05=PlayerOptionsPanel:XNAPanel
$CC06=lblMapName:XNALabel
$CC07=lblMapAuthor:XNALabel
$CC08=lblGameMode:XNALabel
$CC09=lblMapSize:XNALabel
$CC12=lbMapList:XNAMultiColumnListBox
$CC13=lblGameModeSelect:XNALabel
$CC14=ddGameMode:XNAClientDropDown
$CC15=tbMapSearch:XNASuggestionTextBox
$CC16=btnPickRandomMap:XNAClientButton
$CC17=PlayerExtraOptionsPanel:PlayerExtraOptionsPanel
$CC18=lbChatMessages:ChatListBox
$CC19=tbChatInput:XNAChatTextBox
$CC20=btnCnCNet:XNALinkButton

; When beta is merged
; $CC24=btnCnCNet2:XNALinkButton
; $CC25=btnCnCNet3:XNALinkButton

[lblName]
Text=Players; in the game its Players, makes more sense than Name actually, eh

[lblSide]
Text=Side

[lblStart]
Text=Start
Visible=true

[lblColor]
Text=Color

[lblTeam]
Text=Team

[ddPlayerStartBase]
Enabled=true
Visible=true

[ddPlayerStart0]
$BaseSection=ddPlayerStartBase

[ddPlayerStart1]
$BaseSection=ddPlayerStartBase

[ddPlayerStart2]
$BaseSection=ddPlayerStartBase

[ddPlayerStart3]
$BaseSection=ddPlayerStartBase

[ddPlayerStart4]
$BaseSection=ddPlayerStartBase

[ddPlayerStart5]
$BaseSection=ddPlayerStartBase

[ddPlayerStart6]
$BaseSection=ddPlayerStartBase

[ddPlayerStart7]
$BaseSection=ddPlayerStartBase

[lbChatMessagesBase]
SolidColorBackgroundTexture=0,0,0,200
Location=12,14
Size=0,234

[lbChatMessages_Host]
$BaseSection=lbChatMessagesBase
FillWidth=740

[lbChatMessages_Player]
$BaseSection=lbChatMessagesBase
FillWidth=740
FillHeight=77

[tbChatInputBase]
Suggestion=Type here to chat...
X=12
Size=0,21
FillWidth=740

[tbChatInput_Host]
$BaseSection=tbChatInputBase
Y=258

[tbChatInput_Player]
$BaseSection=tbChatInputBase
DistanceFromBottomBorder=46
FillWidth=830

[lblGameModeSelect]
Location=12,291;180,15
Text=GAME MODE:

[ddGameMode]
Location=246,289
Size=200,21
DistanceFromRightBorder=935;770
FillWidth=850;740

[lbMapList]
SolidColorBackgroundTexture=0,0,0,200
Location=12,315
Size=0,0
FillHeight=77
FillWidth=850;740         

[tbMapSearch]
Location=12,0;162,0
Size=0,21
DistanceFromBottomBorder=46
FillWidth=850;740
Suggestion=Search map...

[PlayerOptionsPanel]
SolidColorBackgroundTexture=0,0,0,200
Location=0,14
Size=400,250;517,250;415,250
DistanceFromRightBorder=437;320

$CC00=btnPlayerExtraOptionsOpen:XNAClientButton

[PlayerExtraOptionsPanel]
SolidColorBackgroundTexture=0,0,0,200
Location=0,14
Size=400,250;517,250;415,250
DistanceFromRightBorder=437;320

[btnPlayerExtraOptionsOpen]
Location=0,0
Enabled=true
Visible=true
$Width=BTN_MENU_OPEN_WIDTH
$Height=BTN_MENU_OPEN_HEIGHT
IdleTexture=optionsButton.png
HoverTexture=optionsButton_c.png

[GameOptionsPanel]
SolidColorBackgroundTexture=0,0,0,200
Location=0,14
Size=420,250;306,250
DistanceFromRightBorder=12

; Left column
$CC-GO01=chkShortGame:GameLobbyCheckBox
$CC-GO02=chkRedeplMCV:GameLobbyCheckBox
$CC-GO03=chkAutoRepair:GameLobbyCheckBox
$CC-GO04=chkMultiEng:GameLobbyCheckBox
$CC-GO05=chkIngameAllying:GameLobbyCheckBox

; Middle column
$CC-GO06=chkDestrBridges:GameLobbyCheckBox
$CC-GO07=chkBuildOffAlly:GameLobbyCheckBox
$CC-GO08=chkRA2Mode:GameLobbyCheckBox
$CC-GO09=chkBalancePatch:GameLobbyCheckBox
$CC-GO10=chkNoSpawnPreviews:GameLobbyCheckBox

; Right column
$CC-GO11=chkNoYuri:GameLobbyCheckBox
$CC-GO12=chkNoFrance:GameLobbyCheckBox
$CC-GO13=chkNoSpy:GameLobbyCheckBox
$CC-GO14=chkNoDogEngiEat:GameLobbyCheckBox
$CC-GO15=chkNoStolenTech:GameLobbyCheckBox

; Drop Down Controls
$CC-GO16=lblCredits:XNALabel
$CC-GO17=cmbCredits:GameLobbyDropDown
$CC-GO18=lblStartingUnits:XNALabel
$CC-GO19=cmbStartingUnits:GameLobbyDropDown
$CC-GO20=lblAIModifier:XNALabel
$CC-GO21=cmbAIModifier:GameLobbyDropDown
$CC-GO22=lblSuperWeapons:XNALabel
$CC-GO23=cmbSuperWeaponsModifier:GameLobbyDropDown
$CC-GO24=lblCratesModifier:XNALabel
$CC-GO25=cmbCratesModifier:GameLobbyDropDown

; New FPS Sliders
$CC-GODD03PH=cmbGameSpeedCapPlaceholder:XNAControl
$CC-GODD04=lblGameSpeedCap:XNALabel

; Save / Load Game Options lul
$CC-G099=btnSaveLoadGameOptions:XNAClientButton

;============================
; LEFT Column Controls
;============================

[chkShortGame]
SpawnIniOption=ShortGame
Checked=True
ToolTip=Players win when all enemy buildings are destroyed.
Text=Short Game
Location=5,5

[chkRedeplMCV]
SpawnIniOption=MCVRedeploy
Checked=True
ToolTip=Players have the ability to move their ConYard after it's deployed.
Text=MCV Repacks
$X=getX(chkShortGame)
$Y=getBottom(chkShortGame) + GAME_OPTION_GAP

[chkAutoRepair]
CustomIniPath=INI\Game Options\Auto Repair.ini
Checked=False
ToolTip=Buildings will automatically repair themselves.
Text=Auto Repair
$X=getX(chkShortGame)
$Y=getBottom(chkRedeplMCV) + GAME_OPTION_GAP

[chkMultiEng]
SpawnIniOption=MultiEngineer
Checked=False
ToolTip=Capturing a structure requires three Engineers instead of one.
Text=Multi Engineer
$X=getX(chkAutoRepair)
$Y=getBottom(chkAutoRepair) + GAME_OPTION_GAP

[chkIngameAllying]
SpawnIniOption=AlliesAllowed
CustomIniPath=INI\Game Options\Allies Allowed.ini
Checked=True
ToolTip=Players can form and break alliances in game.
Text=Ingame Allying
$X=getX(chkMultiEng)
$Y=getBottom(chkMultiEng) + GAME_OPTION_GAP

;============================
; Middle Column Controls
;============================

[chkDestrBridges]
SpawnIniOption=BridgeDestroy
Checked=True
ToolTip=You can destroy low bridges by force-firing on them.
Text=Destroyable Bridges
$Y=5
$X=getX(chkShortGame) + 118

[chkBuildOffAlly]
SpawnIniOption=BuildOffAlly
Checked=True
ToolTip=Check to allow players to build near their allies' construction yards.
Text=Build Off Ally ConYards
$Y=getBottom(chkDestrBridges) + GAME_OPTION_GAP
$X=getX(chkDestrBridges)

[chkRA2Mode]
SpawnIniOption=Ra2Mode
DefaultValue=False
ToolTip=Red Alert 2 Classic Mode will turn gameplay into Red Alert 2.
Text=Red Alert 2
DisallowedSideIndex=9
$Y=getBottom(chkBuildOffAlly) + GAME_OPTION_GAP
$X=getX(chkDestrBridges)

[chkBalancePatch]
CustomIniPath=INI\Game Options\Yuri Rebalance Patch.ini
DefaultValue=False
ToolTip=Yuri's Revenge Rebalance 2.0@Patch notes: https://forums.cncnet.org/topic/11738-yuris-revenge-rebalanced-20/
Text=YR Rebalance 2.0
$Y=getBottom(chkRA2Mode) + GAME_OPTION_GAP
$X=getX(chkDestrBridges)

[chkNoSpawnPreviews]
CustomIniPath=INI\Game Options\No Spawn Previews.ini
DefaultValue=False
ToolTip=Start locations for players won't be shown in the loading screen.
Text=No Spawn Previews
$Y=getBottom(chkBalancePatch) + GAME_OPTION_GAP
$X=getX(chkDestrBridges)

;============================
; Right Column Controls
;============================

[chkNoYuri]
CustomIniPath=INI\Game Options\No_Yuri.ini
DefaultValue=False
ToolTip=Yuri is disabled
Text=No Yuri
DisallowedSideIndices=9
$Y=5
$X=getX(chkDestrBridges) + 154

[chkNoFrance]
CustomIniPath=INI\Game Options\No_France.ini
DefaultValue=False
ToolTip=France is disabled
Text=No France
DisallowedSideIndices=2
$Y=getBottom(chkNoYuri) + GAME_OPTION_GAP
$X=getX(chkNoYuri)

[chkNoSpy]
CustomIniPath=INI\Game Options\No_Spy.ini
DefaultValue=False
ToolTip=Spies are disabled
Text=No Spy
$Y=getBottom(chkNoFrance) + GAME_OPTION_GAP
$X=getX(chkNoFrance)

[chkNoDogEngiEat]
CustomIniPath=INI\Game Options\No Dog Engi Eat.ini
Checked=False
ToolTip=Dogs will be unable to kill Engineers.
Text=No Dog Engineer Kills
$X=getX(chkNoSpy)
$Y=getBottom(chkNoSpy) + GAME_OPTION_GAP

[chkNoStolenTech]
CustomIniPath=INI\Game Options\No Stolen Tech.ini
Checked=False
ToolTip=Stolen Tech is disabled
Text=No Stolen Tech
DataWriteMode=MapCode
$X=getX(chkNoDogEngiEat)
$Y=getBottom(chkNoDogEngiEat) + GAME_OPTION_GAP

;============================
; Drop Down Controls
;============================

[lblGameSpeedCap]
Text=Game Speed:
$Height=DEFAULT_LBL_HEIGHT
$X=getX(cmbGameSpeedCapPlaceholder)
$Y=getBottom(chkIngameAllying) + 10

[cmbGameSpeedCap]
OptionName=Game Speed
DefaultIndex=0
SpawnIniOption=GameSpeed
DataWriteMode=Index
ToolTip=Sets Maximum FPS
$Width=getWidth(cmbGameSpeedCapPlaceholder)
$Height=getHeight(cmbGameSpeedCapPlaceholder)
$X=getX(chkShortGame)
$Y=getBottom(lblGameSpeedCap) + 6

[cmbGameSpeedCapPlaceholder]
Visible=false
Enabled=false
$Width=112;GAME_OPTION_DD_WIDTH
$Height=DEFAULT_CONTROL_HEIGHT
$X=getX(cmbCredits)
$Y=getY(lblCredits)

[lblCredits]
Text=Credits:
$X=getX(chkIngameAllying)
$Y=getBottom(chkIngameAllying) + 50

[cmbCredits]
OptionName=Starting Credits
ToolTip=Credits at the start of the game.
Items=100000,30000,20000,15000,12500,10000,7500,5000,2500
DefaultIndex=5
SpawnIniOption=Credits
DataWriteMode=String
$X=getX(lblCredits)
$Y=getBottom(lblCredits)
$Width=112;GAME_OPTION_DD_WIDTH
$Height=DEFAULT_CONTROL_HEIGHT

[lblStartingUnits]
Text=Starting Units:
$Y=getBottom(cmbCredits) + GAME_OPTION_GAP
$X=getX(chkShortGame)

[cmbStartingUnits]
OptionName=Starting Units
ToolTip=Starting Units at the beginning of the game.
Items=10,9,8,7,6,5,4,3,2,1,0
DefaultIndex=10
SpawnIniOption=UnitCount
DataWriteMode=String
DistanceFromRightBorder=51
$Y=getBottom(lblStartingUnits)
$X=getX(chkShortGame)
$Width=112;GAME_OPTION_DD_WIDTH
$Height=DEFAULT_CONTROL_HEIGHT

[lblSuperWeapons]
Text=Super Weapons:
$Height=DEFAULT_LBL_HEIGHT
$X=getX(chkNoSpawnPreviews)
$Y=getBottom(chkNoSpawnPreviews) + 10

[cmbSuperWeaponsModifier]
ToolTip=Super Weapons Settings
OptionName=SuperWeapon Settings:
ItemLabels=Enabled,Offensive,Defensive,Disabled
Items=INI\Game Options\SuperWeapons\All.ini,INI\Game Options\SuperWeapons\Offensive.ini,INI\Game Options\SuperWeapons\Defensive.ini,INI\Game Options\SuperWeapons\Disabled.ini
DefaultIndex=0
SpawnIniOption=String
DataWriteMode=MapCode
$X=getX(chkDestrBridges)
$Y=getBottom(lblSuperWeapons) + 6
$Width=120;GAME_OPTION_DD_WIDTH
$Height=DEFAULT_CONTROL_HEIGHT

[lblAIModifier]
Text=AI Modifier:
$X=getX(chkNoSpawnPreviews)
$Y=getY(lblCredits)

[cmbAIModifier]
ToolTip=Set the behaviour of the Computer AI.
OptionName=AI Modifier
ItemLabels=Vanilla AI,Brutal AI,Extreme AI
Items=INI\Game Options\AI\No Change.ini,INI\Game Options\AI\Brutal AI.ini,INI\Game Options\AI\Extreme AI.ini
DefaultIndex=0
SpawnIniOption=String
DataWriteMode=MapCode
$X=getX(lblAIModifier)
$Y=getBottom(lblAIModifier)
$Width=120;$Width=GAME_OPTION_DD_WIDTH
$Height=DEFAULT_CONTROL_HEIGHT

[lblCratesModifier]
Text=Crate Settings:
$X=getX(chkNoSpawnPreviews)
$Y=getY(lblStartingUnits)

[cmbCratesModifier]
ToolTip=Adjust the number of crates.
OptionName=Crate Settings
ItemLabels=Disabled,Enabled - Default,Enabled - Extra,Enabled - Extreme
Items=INI\Game Options\Crates\Disabled.ini,INI\Game Options\Crates\Enabled.ini,INI\Game Options\Crates\Increased.ini,INI\Game Options\Crates\Super Increased.ini
DefaultIndex=0
SpawnIniOption=String
DataWriteMode=MapCode
$X=getX(lblCratesModifier)
$Y=getBottom(lblCratesModifier)
$Width=120;$Width=GAME_OPTION_DD_WIDTH
$Height=DEFAULT_CONTROL_HEIGHT

;============================
; End of Controls 
;============================

[btnSaveLoadGameOptions]
$Width=BTN_MENU_OPEN_WIDTH
$Height=BTN_MENU_OPEN_WIDTH
Location=0,0
DistanceFromRightBorder=0
IdleTexture=comboBoxArrow.png
HoverTexture=comboBoxArrow.png

[MapPreviewBox]
SolidColorBackgroundTexture=0,0,0,200
Location=406,270
Size=825,0;723,0
FillHeight=77
DistanceFromRightBorder=12

[lblMapName]
Text=.
$Height=DEFAULT_LBL_HEIGHT
$Width=getWidth(MapPreviewBox)
$TextAnchor=RIGHT
$AnchorPoint=getX(MapPreviewBox),getBottom(MapPreviewBox)

[lblMapAuthor]
Text=.
$Height=DEFAULT_LBL_HEIGHT
$Width=getWidth(MapPreviewBox)
$TextAnchor=LEFT
$AnchorPoint=getRight(MapPreviewBox),getBottom(MapPreviewBox)

[lblMapSize]
Visible=false

[lblGameMode]
Text=.
Size=200,10
$X=getX(lblMapName)
$Y=getBottom(lblMapName)

[btnLaunchGame]
Location=12,0
DistanceFromBottomBorder=13
Text=Launch Game
Size=133,23
ClickSoundEffect=button.wav

[btnLeaveGame]
Text=Leave Game
Location=0,0
Size=133,23
DistanceFromBottomBorder=13
DistanceFromRightBorder=12

[btnPickRandomMap]
Location=150,0;267,0;12,0
DistanceFromBottomBorder=13;46
Size=133,23
Text=Pick Random Map

[btnCnCNet]
Location=0,0
Size=133,23
FillWidth=740
DistanceFromBottomBorder=13
IdleTexture=logo.png
HoverTexture=logo.png
DrawMode=Stretched
DrawBorders=false
URL=https://cncnet.org/red-alert-2
ToolTip=CnCNet - Red Alert 2 & Yuri's Revenge Online
$X=getX(lblMapName) - 5
$Y=getBottom(lblMapName) + 25

[btnCnCNet2]
Location=0,0
Size=73,23
FillWidth=740
DistanceFromBottomBorder=13
IdleTexture=logo-2.png
HoverTexture=logo-2.png
DrawMode=Stretched
DrawBorders=false
URL=https://github.com/Phobos-developers/Phobos
ToolTip=Ares-compatible C&C Red Alert 2: Yuri's Revenge engine extension
$X=getX(lblMapName) + 170
$Y=getBottom(lblMapName) + 25

[btnCnCNet3]
Location=0,0
Size=32,23
FillWidth=740
DistanceFromBottomBorder=13
IdleTexture=logo-3.png
HoverTexture=logo-3.png
DrawMode=Stretched
DrawBorders=false
URL=https://ares.strategy-x.com/
ToolTip=Ares is the next generation of binary-based Command & Conquer modding.
$X=getX(lblMapName) + 275
$Y=getBottom(lblMapName) + 25
