[GenericWindow]
DrawMode=Stretched
;Size=350,480
;Padding=16,8,16,8
DrawBorders=true

[LoadingScreen]
Size=1920,1080
BackgroundTexture=loading.png

[SkirmishLobby]
DrawMode=Stretched
DrawBorders=false
Size=1220,768
FillWidth=12
FillHeight=32

[MultiplayerGameLobby]
DrawMode=Stretched
DrawBorders=false
Size=1220,768
FillWidth=12
FillHeight=32

[CnCNetLobby]
DrawMode=Stretched
DrawBorders=false
Size=1220,768
FillWidth=60
FillHeight=32

[PrivacyNotification]
BackgroundTexture=nopreview.png
DrawBorders=false
DrawMode=Stretched

[GameInProgressWindow]
DrawMode=Stretched
BackgroundTexture=nopreview.png
DrawBorders=false
DrawMode=Stretched

[ExtraControls]
0=rabt:XNAExtraPanel
1=rabb:XNAExtraPanel
2=rabl:XNAExtraPanel
3=rabr:XNAExtraPanel
4=ractl:XNAExtraPanel
5=ractr:XNAExtraPanel
6=racbl:XNAExtraPanel
7=racbr:XNAExtraPanel

[StatisticsWindow]
DrawMode=Stretched
BackgroundTexture=statisticsbg.png
DrawBorders=false

[UpdateWindow]
DrawMode=Stretched
BackgroundTexture=msgboxform.png

[UpdateQueryWindow]
DrawMode=Stretched
BackgroundTexture=msgboxform.png


;These need to be unhardcoded

[PrivateMessageNotificationBox]
DrawMode=Stretched
BackgroundTexture=msgboxform.png

[PrivateMessagingPanel]
DrawMode=Stretched
BackgroundTexture=msgboxform.png

[PrivateMessagingWindow]
DrawMode=Stretched
BackgroundTexture=msgboxform.png
DrawBorders=false

[PasswordRequestWindow]
DrawMode=Stretched
BackgroundTexture=msgboxform.png

[panelGameStatistics]
DrawMode=Stretched
BackgroundTexture=50percenttransparent.png ;Yey hacks

[panelTotalStatistics]
DrawMode=Stretched
BackgroundTexture=50percenttransparent.png ;Yey hacks

[CnCNetLoginWindow]
DrawMode=Tiled
DrawBorders=true

[GameCreationWindow]
DrawMode=Tiled

[LANGameCreationWindow]
DrawMode=Tiled