[INISystem]
BasedOn=GameLobbyBase.ini

[MultiplayerGameLobby]
$BaseSection=GameLobbyBase
PlayerReadyBoxX=1
PlayerReadyBoxY=2
PlayerOptionLocationX=25
PlayerOptionLocationY=25
PlayerOptionVerticalMargin=7
PlayerOptionHorizontalMargin=2
PlayerOptionCaptionLocationY=6
PlayerNameWidth=90
SideWidth=120
ColorWidth=80
StartWidth=35
TeamWidth=35

; controls
$CCMP00=btnLockGame:XNAClientButton
$CCMP01=chkAutoReady:XNAClientCheckBox
$CCMP02=tbChatInput:XNAChatTextBox
$CCMP03=lbChatMessages:ChatListBox

[lbMapList]
$Height=291

[tbMapSearch]
Suggestion=Search map...
$Width=getRight(lbMapList) - getRight(btnPickRandomMap) - LOBBY_PANEL_SPACING
$Height=DEFAULT_BUTTON_HEIGHT
$X=getRight(btnPickRandomMap) + LOBBY_PANEL_SPACING
$Y=getY(btnPickRandomMap)
BackColor=255,255,255

[btnPickRandomMap]
$Width=BUTTON_WIDTH_133
$Height=DEFAULT_BUTTON_HEIGHT
$X=LOBBY_EMPTY_SPACE_SIDES
$Y=getBottom(lbMapList) + LOBBY_PANEL_SPACING

[lbChatMessagesBase]
SolidColorBackgroundTexture=0,0,0,200
$Width=getWidth(lbMapList)
$X=LOBBY_EMPTY_SPACE_SIDES

[lbChatMessages_Host]
$BaseSection=lbChatMessagesBase
$Y=getBottom(btnPickRandomMap) + LOBBY_PANEL_SPACING
$Height=getBottom(MapPreviewBox) - (getBottom(btnPickRandomMap) + LOBBY_PANEL_SPACING)

[lbChatMessages_Player]
$BaseSection=lbChatMessagesBase
$Y=EMPTY_SPACE_TOP
$Height=getBottom(MapPreviewBox) - (getY($Self))

[tbChatInputBase]
Suggestion=Type here to chat...
$Width=getWidth(lbMapList)
$Height=DEFAULT_CONTROL_HEIGHT
$X=LOBBY_EMPTY_SPACE_SIDES
$Y=getBottom(MapPreviewBox) + LOBBY_PANEL_SPACING

[tbChatInput_Host]
$BaseSection=tbChatInputBase

[tbChatInput_Player]
$BaseSection=tbChatInputBase

[btnLockGame]
$Width=BUTTON_WIDTH_133
$Height=DEFAULT_BUTTON_HEIGHT
$X=getRight(btnLaunchGame) + LOBBY_PANEL_SPACING
$Y=getY(btnLaunchGame)

[chkAutoReady]
Text=Auto-Ready
$X=getRight(btnLaunchGame) + LOBBY_PANEL_SPACING
$Y=getY(btnLaunchGame) + 2
Enabled=true
Visible=true

[btnSaveLoadGameOptions]
$Width=BTN_MENU_OPEN_WIDTH
$Height=BTN_MENU_OPEN_WIDTH
$X=getWidth($ParentControl) - getWidth($Self)
$Y=0
IdleTexture=comboBoxArrow.png
HoverTexture=comboBoxArrow.png

[GameOptionsPanel]
$CC-GODD03=cmbGameSpeedCapMultiplayer:GameLobbyDropDown

[cmbGameSpeedCapMultiplayer]
$BaseSection=cmbGameSpeedCap
Items=60 FPS,45 FPS,30 FPS,20 FPS,15 FPS,12 FPS,10 FPS
