[INISystem]
BasedOn=GameLobbyBase.ini

[MultiplayerGameLobby]
$BaseSection=GameLobbyBase
PlayerReadyBoxY=2
PlayerReadyBoxX=2
PlayerOptionLocationX=22
PlayerOptionLocationY=25
PlayerOptionVerticalMargin=7
PlayerOptionHorizontalMargin=2
PlayerOptionCaptionLocationY=6
PlayerNameWidth=102                     ;132
SideWidth=120                           ;106
ColorWidth=76                           ;70
StartWidth=32                           ;36   
TeamWidth=32                            ;36

; controls
$CCMP00=btnLockGame:XNAClientButton
$CCMP01=chkAutoReady:XNAClientCheckBox

[lbMapList]
SolidColorBackgroundTexture=0,0,0,200
Location=12,315
Size=0,0
FillHeight=77
FillWidth=828;740

[MapPreviewBox]
Size=808,0;723,0

[PlayerOptionsPanel]
Size=400,250;500,250;415,250
DistanceFromRightBorder=430;320

[tbMapSearch]
Location=12,0;162,0
Size=0,21
DistanceFromBottomBorder=46
FillWidth=828;740
Suggestion=Search map...

[ddGameMode]
Location=246,289
Size=200,21
DistanceFromRightBorder=935;770
FillWidth=828;740

[lbChatMessagesBase]
SolidColorBackgroundTexture=0,0,0,200
Location=12,14
Size=0,234

[lbChatMessages_Host]
$BaseSection=lbChatMessagesBase
FillWidth=828;740

[lbChatMessages_Player]
$BaseSection=lbChatMessagesBase
FillWidth=828;740
FillHeight=77

[tbChatInputBase]
Suggestion=Type here to chat...
X=12
Size=0,21
FillWidth=828;740

[tbChatInput_Host]
$BaseSection=tbChatInputBase
FillWidth=828;740
Y=258

[tbChatInput_Player]
$BaseSection=tbChatInputBase
DistanceFromBottomBorder=46

[btnLockGame]
Location=150,0;157,0
Size=133,23
DistanceFromBottomBorder=13

[btnPickRandomMap]
Location=288,0;12,0
DistanceFromBottomBorder=13;46
Size=133,23
Text=Pick Random Map

[chkAutoReady]
Location=157,0
DistanceFromBottomBorder=14
Visible=true
Enabled=true
Text=Auto-Ready

[GameOptionsPanel]
$CC-GODD03=cmbGameSpeedCapMultiplayer:GameLobbyDropDown

[cmbGameSpeedCapMultiplayer]
$BaseSection=cmbGameSpeedCap
Items=Fastest (60 FPS),Faster (45 FPS),Fast (30 FPS),Medium (20 FPS),Slow (15 FPS),Slower (12 FPS),Slowest (10 FPS)