[OptionsWindow]
DrawMode=Stretched
BackgroundTexture=ModalBG.png

; ==========================
; Audio Menu Options
; ==========================
[AudioOptionsPanelExtraControls]
0=chkTaunts:SettingCheckBox

[chkTaunts]
Location=170,126
Text=Allow Taunts
DefaultValue=true
SettingSection=Options
SettingKey=AllowTaunts

; ==========================
; Game Menu Options
; ==========================
[GameOptionsPanelExtraControls]
0=chkAllowChat:SettingCheckBox
1=chkBuildingPlacement:SettingCheckBox
2=chkQuickExit:SettingCheckBox
3=chkSkipScoreScreen:SettingCheckBox
4=chkSpeedControl:SettingCheckBox
5=chkPrioritySelection:SettingCheckBox
6=chkHarvesterCounter:SettingCheckBox
7=chkPowerDelta:SettingCheckBox
8=chkRealTimeTimers:SettingCheckBox

[lblPlayerName]
Location=12,236

[tbPlayerName]
Location=113,234

[btnConfigureHotkeys]
Location=12,314

[lblNotice]
Location=12,264

; Left Side Toggles
[chkScrollCoasting]
Location=12,54
ToolTip=Enable smooth scrolling.
DefaultValue=true
SettingSection=Options
SettingKey=DisableEdgeScrolling
EnabledSettingValue=false
DisabledSettingValue=true

[chkTargetLines]
Location=12,78
ToolTip=Show lines between selected units and targets.@Green lines indicate movement, red lines attack.

[chkQuickExit]
Location=12,102
Text=Quick Exit
ToolTip=When enabled, you can exit the game by pressing Alt+F4
DefaultValue=true
SettingSection=Options
SettingKey=QuickExit

[chkTooltips]
Location=12,126
ToolTip=Enable in-game tooltips.

[chkAllowChat]
Location=12,150
Text=Allow Chat
ToolTip=When disabled, you will not be able to send or receive messages in-game.
DefaultValue=true
SettingSection=Options
SettingKey=AllowChat

[chkSkipScoreScreen]
Location=12,174
Text=Skip Score Screen
ToolTip=Return to main menu immediately after a game is finished.
DefaultValue=false
SettingSection=Options
SettingKey=SkipScoreScreen

[chkRealTimeTimers]
Location=12,198
Text=Real Time Timers
ToolTip=When enabled timers will use real time instead of game time.
DefaultValue=true
SettingSection=Phobos
SettingKey=RealTimeTimers

; Right Side Toggles
[chkPrioritySelection]
Location=242,54
Text=Mass Selection Filtering
ToolTip=If enabled, non-combat units are not selected if mass-selecting together with combat units.
DefaultValue=false
SettingSection=Phobos
SettingKey=PrioritySelectionFiltering

[chkSpeedControl]
Location=242,78
Text=Control Campaign Speed
ToolTip=When enabled, you can change the game speed while playing the campaign@This option is not normally available for campaign mode
DefaultValue=false
SettingSection=Options
SettingKey=SpeedControl

[chkPowerDelta]
Location=242,102
Text=Show Power Delta
ToolTip=If enabled, an additional counter near your credits indicator will show power delta (total - consumption).
DefaultValue=false
SettingSection=Phobos
SettingKey=ShowPowerDelta

[chkShowHiddenObjects]
Location=242,126
ToolTip=Display a visual indicator when an object is visually hidden behind something.

[chkHarvesterCounter]
Location=242,150
Text=Show Harvester Counter
ToolTip=If enabled, an additional counter near your credits indicator will show active and total harvester counts.
DefaultValue=false
SettingSection=Phobos
SettingKey=ShowHarvesterCounter

[chkBuildingPlacement]
Location=242,174
Text=Show Building Placement Preview
ToolTip=When enabled, shows a preview image of the building when placing it
DefaultValue=false
SettingSection=Phobos
SettingKey=ShowPlacementPreview

; ==========================
; Updater Menu Items
; ==========================
[UpdaterOptionsPanelExtraControls]
0=lblUpdateChannel:XNALabel
1=ddUpdateChannel:FileSettingDropDown
2=lblUpdateChannelDescription:XNALabel
5=btnCncnetSupport:XNALinkButton

[lblUpdateChannel]
Location=12,240
Size=90,24
Text=Update Channel:

[btnForceUpdate]
Location=407,213
Size=133,23

[ddUpdateChannel]
Location=102,238
Size=135,21
Items=Live,Pre-release,Dev,Legacy (Unsupported)
DefaultValue=0
CheckFilePresence=yes
ResetUnselectableItem=yes
ForceApplyUnselectableItem=no
RestartRequired=true
Item0File0=Resources/Config/UpdaterConfig_Live.ini,updateconfig.ini,OverwriteOnMismatch
Item1File0=Resources/Config/UpdaterConfig_PreRelease.ini,updateconfig.ini,OverwriteOnMismatch
Item2File0=Resources/Config/UpdaterConfig_Dev.ini,updateconfig.ini,OverwriteOnMismatch
Item3File0=Resources/Config/UpdaterConfig_Legacy.ini,updateconfig.ini,OverwriteOnMismatch
ToolTip=Switch between update Channels. Requires client restart.
Enabled=true

[lblUpdateChannelDescription]
Location=12,264
Text=**WARNING**: Using a non-live channel may bring unexpected errors or behavior.@Non-live channels are meant to allow public testing of upcoming features before they are released.@Please use Discord to report any issues and be sure to mention the Update Channel you are using.

[btnCncnetSupport]
Location=12,315
Size=133,21
Text=CnCNet Support
URL=https://discord.com/channels/188156159620939776/1060560955186085888
IdleTexture=133pxbtn.png
HoverTexture=133pxbtn_c.png
