[INISystem]
BasedOn=..\GlobalThemeSettings.ini

[General]
UILabelColor=255,255,0
DisabledButtonColor=128,128,128
AltUIColor=255,255,0
AltUIBackgroundColor=20,20,20,255
ButtonHoverColor=255,255,128
AdminNameColor=255,0,0
PlayerNameColor=255,255,50
DefaultChatColor=255,255,50
PrivateMessageColor=160,160,160
PrivateMessageOtherUserColor=196,64,64
LockedGameColor=128,128,128
ListBoxFocusColor=248,0,0
ListBoxHeaderColor=255,255,255
HoverOnGameColor=128,0,0
TrackBarBackgroundColor=0,0,0
TrackBarBackgroundColor=10,10,10
PanelBorderColor=128,0,0
WindowBorderColor=128,0,0
DropDownBorderColor=128,0,0
StartingLocationHoverColor=255,0,0,128
HintTextColor=255,255,255
MapPreviewNameBackgroundColor=0,0,0,144
MapPreviewNameBorderColor=0,0,0,72
MainMenuTheme=Yuri Theme\MainMenuTheme

[GameLobby]
ComboBoxOutlineColor=204,0,0
CoopBriefingForeColor=255,0,0
HoverOnGameColor=5,13,30



;[INISystem]
;BasedOn=..\GlobalThemeSettings.ini
;;Use GlobalThemeSettings.ini to configure the global theme settings.
;[General]
;UILabelColor=255,255,0
;AltUIColor=255,255,0 ; 255,255,255 ;this changes a lot of text that should be UILabelColor and the progress bar as well
;PlayerNameColor=255,255,0
;DefaultChatColor=255,255,0
;DefaultPersonalChatColorIndex=3
;DefaultChannel=YR
;PrivateMessageOtherUserColor=196,64,64
;ListBoxFocusColor=248,0,0
;TrackBarBackgroundColor=40,4,0	;80,8,0
;PanelBorderColor=165,189,198
;WindowBorderColor=255,24,24
;StartingLocationHoverColor=255,0,0,128
;HintTextColor=255,255,255
;AlphaRate=0.015
