[yr]
GameExe="gamemd-spawn.exe"
; New
Launch=SyringeEx.exe -i=Ares.dll -i=CnCNet-Spawner.dll -i=Phobos.dll %GameExe% --args="-CD -SPAWN -LOG -RA2ModeSaveID=0x8d143b95"
; Old
; Launch=Syringe.exe -i=Ares.dll -i=CnCNet-Spawner.dll -i=Phobos.dll %GameExe% -CD -SPAWN -LOG -RA2ModeSaveID=0x8d143b95
ExceptionFileName=except.txt
