[yr]
GameExe=gamemd-spawn.exe
; New
; Launch=SyringeEx.exe -i=Ares.dll -i=CnCNet-Spawner.dll -i=Phobos.dll %GameExe% --args="-SPAWN -LOG -CD -Include -Inheritance -RA2ModeSaveID=0x8d113b94"
; Old
Launch=Syringe.exe -i=Ares.dll -i=CnCNet-Spawner.dll -i=Phobos.dll "%GameExe%" -SPAWN -LOG -CD -Include -Inheritance -RA2ModeSaveID=0x8d113b94
ExceptionFileName=except.txt
