name: build installer

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build-installer:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Installer
      run: build_installer.bat
      shell: cmd
      working-directory: ./InnoSetup
      
    - uses: actions/upload-artifact@v2
      name: Upload Artifacts
      with:
        name: artifacts
        path: ./InnoSetup/output